Repository SkyblockerMod/Skyblocker, pull requests merged in 2023-10, with the labels that each got.

#334 Config Tweaks
  src/main/java/me/xmrvizzy/skyblocker/config/ConfigUtils.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/DiscordRPCCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/DwarvenMinesCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/GeneralCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/LocationsCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/MessageFilterCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/QuickNavigationCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/SlayersCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/controllers/EnumDropdownController.java
  src/main/java/me/xmrvizzy/skyblocker/config/controllers/EnumDropdownControllerBuilder.java
  src/main/java/me/xmrvizzy/skyblocker/config/controllers/EnumDropdownControllerBuilderImpl.java
  src/main/java/me/xmrvizzy/skyblocker/config/controllers/EnumDropdownControllerElement.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: enhancement

#342 Update shortcuts description
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#340 Item Rarity Backgrounds
  src/main/java/me/xmrvizzy/skyblocker/SkyblockerMod.java
  src/main/java/me/xmrvizzy/skyblocker/config/ConfigUtils.java
  src/main/java/me/xmrvizzy/skyblocker/config/SkyblockerConfig.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/GeneralCategory.java
  src/main/java/me/xmrvizzy/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/me/xmrvizzy/skyblocker/mixin/InGameHudMixin.java
  src/main/java/me/xmrvizzy/skyblocker/skyblock/item/ItemRarityBackgrounds.java
  src/main/java/me/xmrvizzy/skyblocker/skyblock/item/SkyblockItemRarity.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/sprites/item_rarity_background.png
Labels: new feature, merge me please

#338 sync MRREADME.md with modrinth description
  MRREADME.md
  build.gradle
Labels: merge me please

#343 Fix recipe book slot textures
  src/main/java/me/xmrvizzy/skyblocker/skyblock/itemlist/ResultButtonWidget.java
Labels: bug, merge me please

#344 Add Support for Custom toString Function for Enum Dropdowns
  src/main/java/me/xmrvizzy/skyblocker/config/ConfigUtils.java
  src/main/java/me/xmrvizzy/skyblocker/config/SkyblockerConfig.java
  src/main/java/me/xmrvizzy/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/me/xmrvizzy/skyblocker/config/controllers/EnumDropdownController.java
  src/main/java/me/xmrvizzy/skyblocker/config/controllers/EnumDropdownControllerBuilder.java
  src/main/java/me/xmrvizzy/skyblocker/config/controllers/EnumDropdownControllerBuilderImpl.java
  src/main/java/me/xmrvizzy/skyblocker/skyblock/dungeon/DungeonChestProfit.java
  src/test/java/me/xmrvizzy/skyblocker/skyblock/dungeon/DungeonChestProfitTest.java
Labels: merge me please

#345 Update Loom and Gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: merge me please

#341 Hook actual durability for Pickonimbus/Drills
  src/main/java/me/xmrvizzy/skyblocker/mixin/DrawContextMixin.java
  src/main/java/me/xmrvizzy/skyblocker/mixin/ItemMixin.java
  src/main/java/me/xmrvizzy/skyblocker/mixin/ItemStackMixin.java
  src/main/java/me/xmrvizzy/skyblocker/utils/ItemUtils.java
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#346 Optimize Scoreboard Stuff
  src/main/java/me/xmrvizzy/skyblocker/skyblock/rift/EffigyWaypoints.java
  src/main/java/me/xmrvizzy/skyblocker/utils/SlayerUtils.java
  src/main/java/me/xmrvizzy/skyblocker/utils/Utils.java
Labels: merge me please

#352 Fix potential NPE
  src/main/java/de/hysky/skyblocker/skyblock/item/CompactorPreviewTooltipComponent.java
Labels: merge me please

#356 fix blaze
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonBlaze.java
Labels: merge me please

#347 Fix Golden Goblin Slayer showing up as Goblin Slayer on commission HUD
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
Labels: merge me please

#354 Refactor Utils
  src/main/java/de/hysky/skyblocker/skyblock/rift/EffigyWaypoints.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/HealingMelonIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/ManiaIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/StakeIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/TwinClawsIndicator.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/discord/DiscordRPCManager.java
Labels: merge me please

#350 Refactor NBT Parsing
  src/main/java/de/hysky/skyblocker/compatibility/emi/SkyblockEmiRecipe.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockCraftingDisplayGenerator.java
  src/main/java/de/hysky/skyblocker/mixin/ArmorTrimMixin.java
  src/main/java/de/hysky/skyblocker/mixin/DrawContextMixin.java
  src/main/java/de/hysky/skyblocker/mixin/DyeableItemMixin.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixin/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/TeleportOverlay.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CompactorDeletorPreview.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorDyeColors.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorTrims.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomItemNames.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemProtection.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemRarityBackgrounds.java
  src/main/java/de/hysky/skyblocker/skyblock/item/PriceInfoTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRegistry.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemStackBuilder.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/SearchResultsWidget.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: merge me please

#359 fix quick nav background texture
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
Labels: merge me please

#360 update issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
Labels: merge me please

#355 Creeper beam puzzle solver
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CreeperBeams.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonBlaze.java
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/id_id.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/ko_kr.json
  src/main/resources/assets/skyblocker/lang/nb_no.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
Labels: new feature, merge me please

#361 Scheduler Multithreaded Support + Refactor
  src/main/java/de/hysky/skyblocker/skyblock/item/PriceInfoTooltip.java
  src/main/java/de/hysky/skyblocker/utils/scheduler/MessageScheduler.java
  src/main/java/de/hysky/skyblocker/utils/scheduler/Scheduler.java
Labels: reviews needed, merge me please

#363 Update Fetchur solver
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/Fetchur.java
Labels: merge me please

#367 Codec-based Test
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorTrims.java
  src/test/java/de/hysky/skyblocker/skyblock/item/ArmorTrimIdSerializationTest.java
Labels: merge me please

#366 Optimize Drill Fuel and Picko Durability with Caching
  src/main/java/de/hysky/skyblocker/mixin/ItemMixin.java
  src/main/java/de/hysky/skyblocker/mixin/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: bug, merge me please

#369 fix issue_template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: reviews needed

#364 Refactor NEU Repo
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/compatibility/emi/SkyblockEmiRecipe.java
  src/main/java/de/hysky/skyblocker/compatibility/emi/SkyblockerEMIPlugin.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockCraftingDisplayGenerator.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREIClientPlugin.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/FairySouls.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CompactorDeletorPreview.java
  src/main/java/de/hysky/skyblocker/skyblock/item/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRegistry.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemStackBuilder.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/SearchResultsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/SkyblockCraftingRecipe.java
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#370 change flame height
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/InGameOverlayRendererMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#371 Secret Waypoint Rendering Customization
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CreeperBeams.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonBlaze.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/TicTacToe.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypoint.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#373 New Message Feedback Prefix
  src/main/java/de/hysky/skyblocker/skyblock/FairySouls.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonSecrets.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorDyeColors.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorTrims.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomItemNames.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemProtection.java
  src/main/java/de/hysky/skyblocker/skyblock/item/PriceInfoTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/skyblock/spidersden/Relics.java
  src/main/java/de/hysky/skyblocker/utils/Constants.java
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/id_id.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/ko_kr.json
  src/main/resources/assets/skyblocker/lang/nb_no.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#374 Remove unused quicknav translation strings
  src/main/java/de/hysky/skyblocker/config/categories/QuickNavigationCategory.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#337 Fix some HUD options resetting sometimes
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/DwarvenMinesCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonMapConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHudConfigScreen.java
  src/main/java/de/hysky/skyblocker/utils/render/title/TitleContainerConfigScreen.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/fabric.mod.json
Labels: merge me please

#377 Patch Float/Double Field Controller Bug
  src/main/java/de/hysky/skyblocker/compatibility/MixinPlugin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/DoubleFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/FloatFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/IntegerFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/LongFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/NumberFieldControllerMixin.java
  src/main/resources/skyblocker.mixins.json
Labels: merge me please

#380 Refactor Durability Parsing
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: merge me please

#330 Mythological Ritual Helper
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/diana/MythologicalRitual.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature

#381 AOTV & Pearl Secret Waypoints
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonMapUtils.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonSecrets.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypoint.java
  src/main/resources/assets/skyblocker/dungeons/secretlocations.json
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#382 Update README.md
  README.md
Labels: merge me please

#383 Enigma Soul Waypoints
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/EnigmaSouls.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/MirrorverseWaypoints.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/TheRift.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/rift/enigma_soul_waypoints.json
  src/main/resources/assets/skyblocker/rift/mirrorverse_waypoints.json
Labels: merge me please

#384 Item Rarity Backgrounds compatibility with Backpack Preview
  src/main/java/de/hysky/skyblocker/skyblock/item/BackpackPreview.java
Labels: merge me please

#385 Fix echo detection activating
  src/main/java/de/hysky/skyblocker/skyblock/diana/MythologicalRitual.java
Labels: merge me please

#387 Refactor Backpack Preview
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/BackpackPreview.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/textures/gui/inventory_background.png
Labels: merge me please

#386 Hypixel Api Proxy + Profile Id Caching
  src/main/java/de/hysky/skyblocker/utils/Http.java
Labels: merge me please

#388 Use Api Redirect
  src/main/java/de/hysky/skyblocker/utils/Http.java
Labels: merge me please

#389 Museum Item Cache
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/TeleportOverlay.java
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/utils/Http.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
Labels: merge me please

#390 Waypoints API & Custom Dungeon Secrets
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/diana/MythologicalRitual.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonSecrets.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypoint.java
  src/main/java/de/hysky/skyblocker/skyblock/item/BackpackPreview.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/Waypoint.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#391 Fix #353
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/GardenSkillsWidget.java
Labels: merge me please

#393 Exotic Tooltip & PriceInfoTooltip Cleanup
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/TeleportOverlay.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonChestProfit.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/BackpackPreview.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/CompactorDeletorPreview.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/CompactorPreviewTooltipComponent.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ExoticTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/java/de/hysky/skyblocker/utils/Constants.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#394 Player Secrets Tracker
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretsTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonPlayerWidget.java
  src/main/java/de/hysky/skyblocker/utils/ApiUtils.java
  src/main/java/de/hysky/skyblocker/utils/Http.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please
