Repository SkyblockerMod/Skyblocker, pull requests merged in 2023-12, with the labels that each got.

#436 Add f3/m3 fire freeze staff timer
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/FireFreezeStaffTimer.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#439 Fix Integer Overflow
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
Labels: bug, merge me please

#443 1.20.3
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/PlayerSkinProviderMixin.java
  src/main/java/de/hysky/skyblocker/mixin/YggdrasilMinecraftSessionServiceMixin.java
  src/main/java/de/hysky/skyblocker/mixin/YggdrasilServicesKeyInfoMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypoint.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretsTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/BackpackPreview.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemStackBuilder.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ResultButtonWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/EffigyWaypoints.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/GardenServerWidget.java
  src/main/java/de/hysky/skyblocker/utils/Constants.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/fabric.mod.json
  src/main/resources/skyblocker.accesswidener
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypointTest.java
Labels: reviews needed

#444 Update mod to 1.16.0+1.20.3
  CHANGELOG.md
  FEATURES.md
  MRREADME.md
  README.md
  gradle.properties
Labels: tester needed

#446 Update Debug Mode
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/debug/DumpPlayersCommand.java
  src/main/java/de/hysky/skyblocker/mixin/EntityRenderDispatcherMixin.java
  src/main/java/de/hysky/skyblocker/mixin/LivingEntityRendererMixin.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/resources/skyblocker.mixins.json
Labels: merge me please

#447 Migrate to upstreamed EnumDropdownController
  src/main/java/de/hysky/skyblocker/config/ConfigUtils.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/controllers/EnumDropdownController.java
  src/main/java/de/hysky/skyblocker/config/controllers/EnumDropdownControllerBuilder.java
  src/main/java/de/hysky/skyblocker/config/controllers/EnumDropdownControllerBuilderImpl.java
  src/main/java/de/hysky/skyblocker/config/controllers/EnumDropdownControllerElement.java
Labels: merge me please

#449 Ignore invalid entity data exceptions & broken quiz question
  src/main/java/de/hysky/skyblocker/mixin/DataTrackerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/Trivia.java
  src/main/resources/skyblocker.mixins.json
Labels: merge me please

#450 Ultimate rarity
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemRarityBackgrounds.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockItemRarity.java
Labels: merge me please

#451 Increase shortcuts character limit & Reset griffin burrows on world change
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/MythologicalRitual.java
Labels: merge me please

#455 Update fabric.mod.json access widener
  src/main/resources/fabric.mod.json
Labels: bug, merge me please

#454 Update Dungeon Puzzles
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/events/DungeonEvents.java
  src/main/java/de/hysky/skyblocker/mixin/BatEntityMixin.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/CreeperBeams.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/DungeonBlaze.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/DungeonPuzzle.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/ThreeWeirdos.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/TicTacToe.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/Trivia.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DebugRoom.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonMapUtils.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypoint.java
  src/main/java/de/hysky/skyblocker/utils/Tickable.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatMessageListener.java
  src/main/java/de/hysky/skyblocker/utils/render/Renderable.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/Waypoint.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/ThreeWeirdosTest.java
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/TriviaTest.java
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonRoomsDFU.java
Labels: merge me please

#456 Item Utils & Random Tests
  build.gradle
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypoint.java
  src/test/java/de/hysky/skyblocker/skyblock/ChestValueTest.java
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypointTest.java
  src/test/java/de/hysky/skyblocker/utils/ItemUtilsTest.java
  src/test/java/de/hysky/skyblocker/utils/PosUtilsTest.java
Labels: merge me please

#457 Suppress unknown scoreboard objective warnings
  gradle.properties
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
Labels: merge me please

#458 remove screens when switching island
  src/main/java/de/hysky/skyblocker/mixin/MinecraftClientMixin.java
  src/main/java/de/hysky/skyblocker/utils/BasePlaceholderScreen.java
  src/main/java/de/hysky/skyblocker/utils/JoinWorldPlaceholderScreen.java
  src/main/java/de/hysky/skyblocker/utils/ReconfiguringPlaceholderScreen.java
Labels: new feature

#460 Suppress badlion packet warnings
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
Labels: bug

#463 More Compatible Colour Parsing
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
Labels: bug

#464 Improve occlusion culling accuracy
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/culling/OcclusionCuller.java
  src/main/java/de/hysky/skyblocker/utils/render/culling/OcclusionCulling.java
  src/main/java/de/hysky/skyblocker/utils/render/culling/ReducedWorldProvider.java
  src/main/java/de/hysky/skyblocker/utils/render/culling/WorldProvider.java
Labels: bug
