Repository SkyblockerMod/Skyblocker, pull requests merged in 2023-11, with the labels that each got.

#396 More cleanup
  src/main/java/de/hysky/skyblocker/compatibility/MixinPlugin.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/java/de/hysky/skyblocker/config/categories/DiscordRPCCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/DwarvenMinesCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/MessageFilterCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/QuickNavigationCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/SlayersCategory.java
  src/main/java/de/hysky/skyblocker/mixin/SocialInteractionsPlayerListWidgetMixin.java
  src/main/java/de/hysky/skyblocker/mixin/YggdrasilServicesKeyInfoMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/FloatFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/IntegerFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/LongFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/NumberFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CreeperBeams.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonMapConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHudConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorTrims.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemRarityBackgrounds.java
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockItemRarity.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/EffigyWaypoints.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Colors.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/PlayerListMgr.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/CommsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonPuzzleWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/FireSaleWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ForgeWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudCommsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/rift/RiftProgressWidget.java
  src/main/java/de/hysky/skyblocker/utils/ApiUtils.java
  src/main/java/de/hysky/skyblocker/utils/Http.java
  src/main/java/de/hysky/skyblocker/utils/SlayerUtils.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatMessageListener.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/title/TitleContainerConfigScreen.java
  src/main/java/de/hysky/skyblocker/utils/scheduler/Scheduler.java
Labels: merge me please

#399 Improve Diana Solver Trigger Accuracy
  src/main/java/de/hysky/skyblocker/skyblock/diana/MythologicalRitual.java
Labels: merge me please

#400 Great Spook Emblem
  src/main/java/de/hysky/skyblocker/utils/Constants.java
Labels: merge me please

#402 Issue template fixes
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
Labels: merge me please

#404 NIO Refactor
  src/main/java/de/hysky/skyblocker/skyblock/FairySouls.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/Shortcuts.java
  src/main/java/de/hysky/skyblocker/skyblock/spidersden/Relics.java
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
Labels: merge me please

#405 The lost translation string
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#406 Livid Color Highlight
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/mixin/WorldRendererMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/MobGlow.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/StarredMobGlow.java
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
Labels: new feature, merge me please

#407 Square Item Rarity Background
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemRarityBackgrounds.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/sprites/item_rarity_background_circular.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/item_rarity_background_square.png
Labels: merge me please

#409 Fix fairy soul solver NPE if we can't connect to NEU repo
  src/main/java/de/hysky/skyblocker/skyblock/FairySouls.java
Labels: merge me please

#410 Update yacl to 3.3.0-beta.1
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/compatibility/MixinPlugin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/DoubleFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/FloatFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/IntegerFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/LongFieldControllerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/yacl/NumberFieldControllerMixin.java
  src/main/resources/skyblocker.mixins.json
Labels: merge me please

#411 Shortcuts fix
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#412 Fix Item Nbt Matching
  src/main/java/de/hysky/skyblocker/compatibility/emi/SkyblockEmiRecipe.java
  src/main/java/de/hysky/skyblocker/compatibility/emi/SkyblockerEMIPlugin.java
Labels: bug, merge me please

#413 Fix Secret Waypoints
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonSecrets.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypoint.java
  src/main/resources/assets/skyblocker/dungeons/secretlocations.json
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypointTest.java
Labels: bug, merge me please

#414 Blobbercyst Glow
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/debug/DumpPlayersCommand.java
  src/main/java/de/hysky/skyblocker/mixin/WorldRendererMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/MobGlow.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: reviews needed, merge me please

#416 Fix Combo Filter
  src/main/java/de/hysky/skyblocker/skyblock/filters/ComboFilter.java
  src/test/java/de/hysky/skyblocker/skyblock/filters/ComboFilterTest.java
Labels: bug, merge me please

#417 Improve Obtained & Museum Item Tooltips
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#415 Batched Rendering + Future Sodium Compat
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/special/SpecialEffects.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/SkyblockerRenderLayers.java
Labels: reviews needed, merge me please

#422 Enhanced Museum Cache Error Handling
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#423 Fix Garden Tab + Small Things
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/MessageFilterCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Ico.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ComposterWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/GardenServerWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/GardenSkillsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/GardenVisitorsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/JacobsContestWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/PowderWidget.java
  src/main/java/de/hysky/skyblocker/utils/Constants.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug

#397 Improve & Fix Compactor Preview
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/CompactorDeletorPreview.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/CompactorPreviewTooltipComponent.java
Labels: bug

#428 Update ChestValue
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/mixin/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/mixin/MinecraftClientMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonChestProfit.java
  src/main/java/de/hysky/skyblocker/skyblock/item/HotbarSlotLock.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/ChestValueTest.java
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/DungeonChestProfitTest.java
Labels: new feature, merge me please

#429 Add Wither & Blood Door Highlight
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonMapUtils.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonSecrets.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#430 Add Config Button in Skyblock Menu
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
Labels: new feature, merge me please

#426 Update DiscordRPCManager
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/mixin/discordipc/ConnectionMixin.java
  src/main/java/de/hysky/skyblocker/utils/discord/DiscordRPCManager.java
  src/main/resources/skyblocker.mixins.json
Labels: bug, merge me please

#427 Update MythologicalRitual
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/MythologicalRitual.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/test/java/de/hysky/skyblocker/skyblock/waypoint/MythologicalRitualTest.java
Labels: merge me please

#438 Gift Giving Emblem
  src/main/java/de/hysky/skyblocker/utils/Constants.java
Labels: reviews needed
