Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-08, with the labels that each got.

#883 Fix Farming Hud Crash
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
Labels: bug, reviews needed, crash

#886 Fix item debug crashes
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: bug, crash, merge me please, small change

#845 Add raytracing to the egg finder to make it fairer
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
  src/main/java/de/hysky/skyblocker/utils/PosUtils.java
  src/main/java/de/hysky/skyblocker/utils/SkyblockTime.java
Labels: bug, merge me please, backport me

#861 Chest Value: Only show minion's generated stuff and visual upgrade
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#873 Kuudra Part 2
  src/main/java/de/hysky/skyblocker/config/categories/CrimsonIsleCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/CrimsonIsleConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/ArrowPoisonWarning.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/DangerWarning.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/Kuudra.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/KuudraWaypoints.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/java/de/hysky/skyblocker/utils/render/title/Title.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#849 Treasure Chest Highlighter for crystal hollows
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/ClientWorldMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsChestHighlighter.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#865 Quick nav tooltip
  src/main/java/de/hysky/skyblocker/config/categories/QuickNavigationCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/QuickNavigationConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNav.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#872 Skyblock XP Messages
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/ChatCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/ChatConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/SkyblockXpMessages.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#893 Added description to hideEmptyTooltips option.
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: documentation, merge me please, small change

#895 Crystal Waypoints server-sided sharing via WebSocket
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/MiningLocationLabel.java
  src/main/java/de/hysky/skyblocker/utils/Http.java
  src/main/java/de/hysky/skyblocker/utils/ws/Payload.java
  src/main/java/de/hysky/skyblocker/utils/ws/Service.java
  src/main/java/de/hysky/skyblocker/utils/ws/SkyblockerWebSocket.java
  src/main/java/de/hysky/skyblocker/utils/ws/Type.java
  src/main/java/de/hysky/skyblocker/utils/ws/WsMessageHandler.java
  src/main/java/de/hysky/skyblocker/utils/ws/WsStateManager.java
  src/main/java/de/hysky/skyblocker/utils/ws/message/CrystalsWaypointMessage.java
  src/main/java/de/hysky/skyblocker/utils/ws/message/Message.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#874 PV Tweaks
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/Inventory.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/PlayerInventory.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/skills/SkillsPage.java
Labels: bug, merge me please, small change

#879 [WORKING DRAFT] Better dungeon door detection/overlay
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonMapUtils.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
Labels: merge me please

#900 Fix Croesus profit estimator on master mode chests
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CroesusProfit.java
Labels: bug, merge me please, small change

#906 Fix clean pickonimbuses showing diamond pickaxe durability
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: bug, merge me please, small change

#907 Fix visitor helper readding visitors after you accept/deny them
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
Labels: bug, merge me please, small change, backport me

#885 True Hex Display for Vincent & Rare Dye Drop Special Effects
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/TrueHexDyeScreenDisplay.java
  src/main/java/de/hysky/skyblocker/skyblock/special/DungeonsSpecialEffects.java
  src/main/java/de/hysky/skyblocker/skyblock/special/DyeSpecialEffects.java
  src/main/java/de/hysky/skyblocker/skyblock/special/SpecialEffects.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/special/DyeSpecialEffectsTest.java
Labels: new feature, merge me please

#902 Fix a lot of config crashes because of null values
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/ConfigNullFieldsFix.java
Labels: bug, crash, merge me please, high priority, small change

#909 Fix quick nav tooltip config
  src/main/java/de/hysky/skyblocker/config/configs/QuickNavigationConfig.java
Labels: bug, crash, merge me please, high priority, small change

#898 1.21.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
  README.md
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/waterboard/Waterboard.java
  src/main/resources/fabric.mod.json
  src/main/resources/skyblocker.accesswidener
Labels: reviews needed, compatibility

#806 Networth
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/java/de/hysky/skyblocker/skyblock/item/PlayerHeadHashCache.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockItemData.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EstimatedItemValueTooltip.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/networth/NetworthCalculator.java
  src/main/java/de/hysky/skyblocker/utils/networth/NetworthDataSuppliers.java
  src/main/java/de/hysky/skyblocker/utils/networth/SkyblockItemMetadataRetriever.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, bleeding edge

#896 Fast util refactor
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/DojoManager.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/ForceTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsChestHighlighter.java
  src/main/java/de/hysky/skyblocker/skyblock/events/EventNotifications.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/ExperimentSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/SuperpairsSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/EditBarWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBarsConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemFixerUpper.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/ProfileViewerScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/collections/GenericCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/dungeons/DungeonMiscStatsWidgets.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/Pet.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/skills/SkillWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java
  src/main/java/de/hysky/skyblocker/utils/Calculator.java
  src/main/java/de/hysky/skyblocker/utils/CodecUtils.java
Labels: merge me please

#917 Crystals Waypoint WebSocket Enhancements
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/java/de/hysky/skyblocker/utils/ws/WsMessageHandler.java
  src/main/java/de/hysky/skyblocker/utils/ws/WsStateManager.java
  src/main/java/de/hysky/skyblocker/utils/ws/message/CrystalsWaypointSubscribeMessage.java
  src/main/java/de/hysky/skyblocker/utils/ws/message/Message.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#918 Fix SuperpairsSolver not starting properly
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/mixins/GenericContainerScreenHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/ChronomatronSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/ExperimentSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/SuperpairsSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/UltrasequencerSolver.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolver.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
Labels: bug, merge me please, tester needed

#897 Chat rules thingamabobs
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRuleAnnouncementScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesHandler.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#921 Fix pet neu id crash
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: merge me please, small change

#928 Update Networth Calculator to fix NPE
  gradle.properties
Labels: bug, crash, merge me please

#923 Fix paul's minister perk not being accounted for
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/java/de/hysky/skyblocker/skyblock/mayors/JerryTimer.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/mayor/Mayor.java
  src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java
  src/main/java/de/hysky/skyblocker/utils/mayor/Minister.java
  src/main/java/de/hysky/skyblocker/utils/mayor/Perk.java
Labels: merge me please

#920 Always load NEU repo
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
Labels: bug, merge me please, small change

#932 Make enums translatable and fix line break issue
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/EventNotificationsConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/QuickNavigationConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/SlayersConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/bazaar/ReorderHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextMode.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/Waypoint.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please, small change

#930 Make Warp Autocomplete adapt to the player's rank
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/WarpAutocomplete.java
  src/main/java/de/hysky/skyblocker/utils/CodecUtils.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/fabric.mod.json
Labels: merge me please

#937 Call ExperimentSolver reset method
  src/main/java/de/hysky/skyblocker/skyblock/experiment/ChronomatronSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/SuperpairsSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/UltrasequencerSolver.java
Labels: bug, merge me please, small change

#936 Mixins Review
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/mixins/ClientWorldMixin.java
  src/main/java/de/hysky/skyblocker/mixins/DyedColorComponentMixin.java
  src/main/java/de/hysky/skyblocker/mixins/GenericContainerScreenHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenProviderMixin.java
  src/main/java/de/hysky/skyblocker/mixins/InventoryScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixins/MinecraftClientMixin.java
  src/main/java/de/hysky/skyblocker/mixins/PingMeasurerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/RenderFishMixin.java
  src/main/java/de/hysky/skyblocker/mixins/SignEditScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixins/SocialInteractionsPlayerListWidgetMixin.java
  src/main/java/de/hysky/skyblocker/mixins/WindowMixin.java
  src/main/java/de/hysky/skyblocker/mixins/accessors/BeaconBlockEntityRendererInvoker.java
Labels: bug, merge me please, small change

#935 Change Rarity Background Default Settings
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
Labels: merge me please, small change

#877 Update Notifications
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/UpdateNotifications.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/UpdateNotificationsTest.java
Labels: new feature, merge me please

#927 Mark all secrets missing in subcommand
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#448 Add JEI integration
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/compatibility/emi/SkyblockEmiRecipe.java
  src/main/java/de/hysky/skyblocker/compatibility/jei/SkyblockCraftingRecipeCategory.java
  src/main/java/de/hysky/skyblocker/compatibility/jei/SkyblockerJEIPlugin.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/SkyblockCraftingRecipe.java
  src/main/java/de/hysky/skyblocker/utils/datafixer/ItemStackComponentizationFixer.java
  src/main/resources/fabric.mod.json
Labels: new feature, merge me please

#913 Proper Item DFU for PV
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/itemLoaders/ItemLoader.java
  src/main/java/de/hysky/skyblocker/skyblock/special/DyeSpecialEffects.java
  src/main/java/de/hysky/skyblocker/utils/datafixer/LegacyItemStackFixer.java
  src/test/java/de/hysky/skyblocker/skyblock/special/DyeSpecialEffectsTest.java
Labels: bug, reviews needed

#926 update skyblocker to 1.22.0
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
  src/main/resources/fabric.mod.json
Labels: merge me please

#785 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/pl_pl.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: reviews needed

#942 Fix Ultrasequencer Bugs
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/UltrasequencerSolver.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolver.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
Labels: bug, merge me please

#953 Fix NoSuchElementException with modelless Abicases
  gradle.properties
Labels: crash, merge me please, small change

#954 Slot Text and Item Protection support for the PV
  src/main/java/de/hysky/skyblocker/mixins/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemProtection.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/BackpackPreview.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/Inventory.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/PlayerInventory.java
Labels: bug, merge me please, small change

#947 Request Profile Id if we don't receive it
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: bug, merge me please

#957 Tooltip Info Rework + Performance improvements
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionBrowserScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/bazaar/BazaarHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/AccessoriesHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/AccessoryTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/AvgBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/BazaarPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/ColorTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/CraftPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EssenceShopPrice.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EstimatedItemValueTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/LBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/MotesTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/MuseumTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/NpcPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/ObtainedDateTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/info/DataTooltipInfo.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/info/DataTooltipInfoType.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/info/SimpleTooltipInfo.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/info/TooltipInfoType.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
  src/main/java/de/hysky/skyblocker/utils/BazaarProduct.java
  src/main/java/de/hysky/skyblocker/utils/CodecUtils.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: merge me please

#959 Fix PV Collections Crash
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/ProfileViewerScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/collections/GenericCategory.java
Labels: bug, crash, merge me please, high priority, small change

#964 Fix WebSocket bugs
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/java/de/hysky/skyblocker/utils/ws/WsStateManager.java
Labels: bug, merge me please, small change

#972 Update mod to 1.22.1 (the aaron update)
  CHANGELOG.md
  gradle.properties
Labels: merge me please

#944 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/nl_nl.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
Labels: reviews needed
