Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-11, with the labels that each got.

#1041 Add math teacher helper
  src/main/java/de/hysky/skyblocker/skyblock/events/greatspook/MathTeacherHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, small change

#1042 Fix NPE when there is no intersection
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/MythologicalRitual.java
Labels: bug, crash, merge me please, high priority

#1025 Add more slot text adders
  src/main/java/de/hysky/skyblocker/skyblock/WardrobeKeybinds.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EvolvingItemAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/NewYearCakeAdder.java
Labels: new feature, merge me please

#1039 Egg finder fix
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
Labels: bug, merge me please

#1045 Fix offhand slot moving around
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockInventoryScreen.java
Labels: bug, merge me please, small change

#1046 Fix slot text not rendering when multiple adders add to same slot
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
Labels: bug, merge me please, small change

#1048 Add colored item dump output
  src/main/java/de/hysky/skyblocker/config/categories/DebugCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DebugConfig.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please, small change

#1050 Fix Glow
  src/main/java/de/hysky/skyblocker/mixins/WorldRendererMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please, high priority

#1053 Fix PV NPE with irregular inventory data
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/InventoryPage.java
Labels: bug, merge me please, small change

#934 Add configurable waypoints for Goldor phase on f7.
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/GoldorWaypointsManager.java
  src/main/resources/assets/skyblocker/dungeons/goldorwaypoints.json
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#973 Shortcuts config fix
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/Shortcuts.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigListWidget.java
Labels: bug, merge me please

#950 Added Purse API and Purse Change Event
  src/main/java/de/hysky/skyblocker/events/SkyblockEvents.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/purse/PurseChangeCause.java
Labels: merge me please

#933 CTRL + F to search inventory
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/InventorySearch.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1023 Fix slot text scaling and update essence adders
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/SalvageHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EssenceShopAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/YourEssenceAdder.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerAndInventorySolver.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolver.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
Labels: bug, merge me please, small change

#1031 Tweak texture positions for quick craft
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreenHandler.java
  src/main/resources/assets/skyblocker/textures/gui/sprites/quick_craft/quick_craft_overlay.png
Labels: merge me please, small change

#1051 add old mushroom hitbox
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/mixins/MushroomPlantBlockMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#1060 Item Stuff
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/injected/SkyblockerStack.java
  src/main/java/de/hysky/skyblocker/mixins/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/PetCache.java
  src/main/java/de/hysky/skyblocker/skyblock/StatusBarTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemRarityBackgrounds.java
  src/main/java/de/hysky/skyblocker/skyblock/item/PetInfo.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/SkyblockIdTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/StackingEnchantProgressTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/Pet.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/itemLoaders/ItemLoader.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/itemLoaders/PetsInventoryItemLoader.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, new feature, merge me please

#1061 Fel Head Glow
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
Labels: new feature, merge me please, small change
