Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-03, with the labels that each got.

#565 Croesus profit calculator
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CroesusHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CroesusProfit.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#576 Fix chat spam
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
Labels: merge me please

#578 Image Repo Loader
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/ConfigUtils.java
  src/main/java/de/hysky/skyblocker/config/ImageRepoLoader.java
  src/main/java/de/hysky/skyblocker/utils/FileUtils.java
  src/main/java/de/hysky/skyblocker/utils/Http.java
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
Labels: new feature, reviews needed

#579 Fix VisitorHelper crash
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
Labels: bug, crash, merge me please

#583 One more creeper beam
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/CreeperBeams.java
Labels: merge me please

#591 32 TAPs for kuudra default
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#593 Fixes error when the directory doesn't exist
  src/main/java/de/hysky/skyblocker/config/ImageRepoLoader.java
Labels: bug, merge me please

#587 Add breaks for force close world loading screen mod
  src/main/resources/fabric.mod.json
Labels: compatibility, merge me please

#592 Fix potential stack overflow with chat rules
  src/main/java/de/hysky/skyblocker/mixin/accessor/BeaconBlockEntityRendererInvoker.java
  src/main/java/de/hysky/skyblocker/mixin/accessor/MessageHandlerAccessor.java
  src/main/java/de/hysky/skyblocker/mixin/accessor/PlayerListHudAccessor.java
  src/main/java/de/hysky/skyblocker/mixin/accessor/RecipeBookWidgetAccessor.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesHandler.java
  src/main/resources/skyblocker.mixins.json
Labels: bug, merge me please

#594 Add Yang Glyph Notification
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/SlayersCategory.java
  src/main/java/de/hysky/skyblocker/mixin/DataTrackerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/accessor/EndermanEntityAccessor.java
  src/main/java/de/hysky/skyblocker/skyblock/end/BeaconHighlighter.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#595 Dungeonmap fix + rewrite
  src/main/java/de/hysky/skyblocker/mixin/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonMap.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
Labels: bug, merge me please

#596 Fix fairy and enigma souls profile loading and add chat profile detection
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/EnigmaSouls.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/FairySouls.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: bug, merge me please

#597 Fix bugs with secret detection
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
  src/main/resources/assets/skyblocker/dungeons/secretlocations.json
Labels: bug, merge me please

#601 Refactor Dwarven, Crystals, and Backpack Preview
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsHud.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/BackpackPreview.java
Labels: merge me please

#582 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/ko_kr.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
Labels: merge me please

#608 Tab hud quick fix
  src/main/java/de/hysky/skyblocker/mixin/PlayerListHudMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#610 Fix #609
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
Labels: bug, crash, merge me please

#612 Update mod to 1.19.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
  .github/workflows/buildrelease.yml
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/resources/fabric.mod.json
Labels: merge me please

#603 Add New Year Cakes Helper
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/accessories/newyearcakes/NewYearCakeBagHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/accessories/newyearcakes/NewYearCakesHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#607 Basic garden mouse locking feature
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/mixin/MouseMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/LowerSensitivity.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#616 Fix Commissions Hud & Wiki Lookup
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
  src/main/java/de/hysky/skyblocker/skyblock/item/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
Labels: bug, crash, merge me please

#619 Redraw square rarity background
  src/main/resources/assets/skyblocker/textures/gui/sprites/item_rarity_background_square.png
Labels: merge me please

#620 Update IF conflict
  src/main/resources/fabric.mod.json
Labels: compatibility, merge me please

#621 Croesus Solver crash fix
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolverManager.java
Labels: bug, merge me please
