Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-10, with the labels that each got.

#1012 fix kings scent detection for wishing compass
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/WishingCompassSolver.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#961 Add debug config and a keybind to dump nearby entities
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/java/de/hysky/skyblocker/config/categories/DebugCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DebugConfig.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/mixins/EntityMixin.java
  src/main/java/de/hysky/skyblocker/mixins/EntityRenderDispatcherMixin.java
  src/main/java/de/hysky/skyblocker/mixins/LivingEntityRendererMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: merge me please

#1018 added 2 items to ItemCooldowns
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
Labels: merge me please

#999 Add SalvageHelper
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/SalvageHelper.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1008 Glacite waypoints (update)
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/MiningLocationLabel.java
Labels: bug, merge me please, small change

#1035 Add clamps to wherever they might be needed in DungeonScore
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java
Labels: bug, merge me please

#1036 Fix Skin Transparency Correction
  src/main/java/de/hysky/skyblocker/skyblock/item/PlayerHeadHashCache.java
Labels: bug, merge me please, high priority, small change

#1037 Fixed NukeKubi Heads not highlighing due to hypixel skin changes update
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
Labels: bug, merge me please, high priority
