Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-09, with the labels that each got.

#978 Fix Egg Finder bugs
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
Labels: bug, merge me please, small change

#980 Block JGit from loading the system Git config
  src/main/java/de/hysky/skyblocker/mixins/jgit/SystemReaderMixin.java
  src/main/resources/skyblocker.mixins.json
Labels: bug, merge me please, small change

#977 mod publish upload changes
  build.gradle
Labels: merge me please

#982 Update NEU repo parser to 1.6.0
  gradle.properties
Labels: merge me please

#975 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/fr_fr.json
Labels: merge me please

#983 Update mod to 1.22.2
  CHANGELOG.md
  README.md
  gradle.properties
Labels: merge me please

#969 Improved vampire icon in profile viewer
  src/main/resources/assets/skyblocker/textures/gui/profile_viewer/vampire.png
Labels: merge me please

#800 Editor Config
  .editorconfig
Labels: merge me please, high priority

#714 Estimated diana burrow pos thing
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/MythologicalRitual.java
Labels: merge me please, tester needed, bleeding edge

#884 BazaarLookup Small Edit
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/bazaar/BazaarHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemPrice.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/AvgBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/BazaarPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/LBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, small change

#945 Added Speed Status Bar #855
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/StatusBarTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/FancyStatusBars.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/icons/speed.png
Labels: new feature, good first issue, merge me please

#943 Add wardrobe helper based on hotbar keybinds
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/WardrobeKeybinds.java
  src/main/java/de/hysky/skyblocker/utils/container/RegexContainerMatcher.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, small change

#1004 Various Fixes
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemFixerUpper.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/ProfileViewerScreen.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/ws/SkyblockerWebSocket.java
  src/main/java/de/hysky/skyblocker/utils/ws/WsMessageHandler.java
Labels: bug, merge me please, small change

#1006 Random fixes
  src/main/java/de/hysky/skyblocker/skyblock/PetCache.java
  src/main/java/de/hysky/skyblocker/skyblock/StatusBarTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/events/EventToast.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockItemRarity.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/BazaarPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EssenceShopPrice.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/UpcomingEventsTab.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
  src/main/java/de/hysky/skyblocker/utils/RegexUtils.java
  src/main/java/de/hysky/skyblocker/utils/SkyblockTime.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/config/DurationController.java
  src/main/java/de/hysky/skyblocker/utils/scheduler/MessageScheduler.java
  src/test/java/de/hysky/skyblocker/utils/ItemUtilsTest.java
Labels: bug, crash, merge me please

#1011 Some Other fixes
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/chat/SkyblockXpMessages.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/Trivia.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/AvgBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/info/DataTooltipInfoType.java
  src/main/resources/resourcepacks/recolored_dungeon_items/pack.mcmeta
Labels: bug, crash, merge me please, small change
