Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-02, with the labels that each got.

#526 Nothing to see here
  src/main/java/de/hysky/skyblocker/utils/Constants.java
  src/test/java/de/hysky/skyblocker/utils/ConstantsTest.java
Labels: new feature, merge me please

#523 Crystal hollows fetures
  MRREADME.md
  README.md
  gradlew.bat
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DwarvenMinesCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsHud.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsHudConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsWaypoint.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHudConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudPowderWidget.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/crystals_map.png
  src/test/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsHudTest.java
  src/test/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationManagerTest.java
Labels: new feature, good first issue, merge me please

#521 Beacon Highlighter performance fix + Fix fire sales widget
  src/main/java/de/hysky/skyblocker/skyblock/end/BeaconHighlighter.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/FireSaleWidget.java
Labels: bug, merge me please

#522 Fix chest value not getting price data under certain circumstances
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
Labels: bug, merge me please

#529 Update IF conflict
  src/main/resources/fabric.mod.json
Labels: bug

#530 Remove 1.20.2 from version selection menu in issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
Labels: merge me please

#532 Add the missing starter commission to the Dwarven HUD.
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
Labels: bug, merge me please

#519 Kuudra Features
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/java/de/hysky/skyblocker/config/categories/CrimsonIsleCategory.java
  src/main/java/de/hysky/skyblocker/mixin/PlayerInventoryMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/ArrowPoisonWarning.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/Kuudra.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/KuudraWaypoints.java
  src/main/java/de/hysky/skyblocker/utils/PosUtils.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/Waypoint.java
  src/main/resources/assets/skyblocker/crimson/kuudra/pearl_waypoints.json
  src/main/resources/assets/skyblocker/crimson/kuudra/safe_spot_waypoints.json
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, reviews needed, merge me please

#534 Disable title and chat messages for Melon/Pumpkin Dicer
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/MessageFilterCategory.java
  src/main/java/de/hysky/skyblocker/mixin/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/filters/DicerFilter.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatMessageListener.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#535 Add Visitor helper
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, good first issue, merge me please

#537 Search overlays for bz and ah
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/java/de/hysky/skyblocker/skyblock/searchOverlay/OverlayScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/searchOverlay/SearchOverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/searchOverlay/SplitStringTest.java
Labels: new feature, merge me please

#524 Add End HUD Widget
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/HudConfigScreen.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EndHudConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EndHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/end/TheEnd.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#540 Boulder Solver
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/boulder/Boulder.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/boulder/BoulderBoard.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/boulder/BoulderObject.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/boulder/BoulderSolver.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#541 Item Quality (dungeon drops)
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#542 Treasure Hoarder Puncher Commission fix
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
Labels: bug, merge me please

#543 center table components in tabhud
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/TableComponent.java
Labels: bug, reviews needed, merge me please

#544 Show the diff in the Powders widget
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/Widget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudPowderWidget.java
Labels: merge me please

#546 Add Item Floor Tier to tooltip
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#547 Better location management
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/Kuudra.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/TheRift.java
  src/main/java/de/hysky/skyblocker/utils/Location.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: merge me please

#548 Small search overlay changes
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/OverlayScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
  src/test/java/de/hysky/skyblocker/skyblock/searchoverlay/SplitStringTest.java
Labels: merge me please

#550 Fix powder hud not updating when commissions hud is disabled
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
Labels: bug, merge me please

#545 Improve secrets caching behaviour
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretsTracker.java
Labels: bug, merge me please

#553 Spider's Den Server Widget
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Ico.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/SpidersDenServerWidget.java
  src/main/resources/assets/skyblocker/tabhud/standard/spider_den.json
  src/main/resources/resourcepacks/top_aligned/assets/skyblocker/tabhud/standard/spider_den.json
Labels: new feature, merge me please

#554 Fix beacon highlights persisting after the boss dies
  src/main/java/de/hysky/skyblocker/skyblock/end/BeaconHighlighter.java
Labels: bug, merge me please

#556 use mod-publish-plugin
  .github/workflows/beta.yml
  .github/workflows/buildrelease.yml
  .github/workflows/webhook_translate.yml
  build.gradle
  gradle.properties
Labels: merge me please

#533 Add Silverfish and Ice Fill Solvers
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/Silverfish.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/waterboard/Waterboard.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFillTest.java
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/SilverfishTest.java
Labels: new feature, merge me please

#558 Support the local memory cache for the API
  src/main/java/de/hysky/skyblocker/utils/Http.java
Labels: merge me please

#561 4 small changes
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixin/InGameOverlayRendererMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#562 Improve Item Protection feature
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixin/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/mixin/MinecraftClientMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemProtection.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/item_protection.png
Labels: merge me please

#563 update mod to 1.18.0
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
Labels: merge me please

#567 Fix clicking in Ultrasequencer
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/UltrasequencerSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolverManager.java
Labels: bug, merge me please

#568 Fix workflow
  .github/workflows/buildrelease.yml
Labels: merge me please

#570 Update mod to 1.18.1
  .github/workflows/beta.yml
  CHANGELOG.md
  gradle.properties
Labels: merge me please

#560 Custom Chat Rules
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/MessageFilterCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRule.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRuleAnnouncementScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRuleConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesConfigListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesHandler.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/chat/ChatRuleTest.java
  src/test/java/de/hysky/skyblocker/skyblock/chat/ChatRulesHandlerTest.java
Labels: new feature, merge me please

#571 Remove no longer used Fetchur riddles
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/Fetchur.java
Labels: merge me please

#573 Tweak particle direction detection
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/MythologicalRitual.java
Labels: merge me please
