Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-04, with the labels that each got.

#617 Fix Dwarven Hud
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
Labels: bug, merge me please

#618 Update Dungeon Secrets (Zodd Room)
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/resources/assets/skyblocker/dungeons/catacombs/1x1/temple-3.skeleton
  src/main/resources/assets/skyblocker/dungeons/catacombs/1x1/zodd-1.skeleton
  src/main/resources/assets/skyblocker/dungeons/dungeonrooms.json
  src/main/resources/assets/skyblocker/dungeons/secretlocations.json
  src/test/resources/assets/skyblocker/dungeons/dungeonrooms.json
  src/test/resources/assets/skyblocker/dungeons/dungeonrooms/catacombs/1x1/Temple-3.skeleton
  src/test/resources/assets/skyblocker/dungeons/dungeonrooms/catacombs/1x1/Zodd-1.skeleton
  src/test/resources/assets/skyblocker/dungeons/secretlocations.json
Labels: merge me please

#626 Remove Visitor from Visitor Helper when you refuse their offer
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
Labels: bug, merge me please

#604 Fix labeler
  .github/workflows/labeler.yml
Labels: merge me please

#628 update mod to 1.19.1
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
Labels: merge me please

#615 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: reviews needed

#599 Make the crafting UI look like the vanilla crafting table
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenProviderMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreenHandler.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/sprites/quick_craft/more_button.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/quick_craft/more_button_disabled.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/quick_craft/more_button_highlighted.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/quick_craft/quick_craft_overlay.png
Labels: new feature, merge me please

#613 Accessories Helper
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/AccessoriesHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#625 Ordered Waypoints
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorDyeColors.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/Waypoint.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#632 Instanced Utils
  src/main/java/de/hysky/skyblocker/utils/InstancedUtils.java
  src/test/java/de/hysky/skyblocker/utils/InstancedUtilsTest.java
Labels: merge me please

#639 fix translate workflow
  .github/workflows/webhook_translate.yml
Labels: merge me please

#630 Warp command auto-complete
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/mixin/CommandTreeS2CPacketMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/WarpAutocomplete.java
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#642 add ability to share crystal waypoint locations
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#629 Add Ender Nodes Helper
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EnderNodes.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#614 Fancy Auctions Browser: The Sequel
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenProviderMixin.java
  src/main/java/de/hysky/skyblocker/mixin/accessor/HandledScreenAccessor.java
  src/main/java/de/hysky/skyblocker/mixin/accessor/SlotAccessor.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionBrowserScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionHouseScreenHandler.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionViewScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/EditBidPopup.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/SlotClickHandler.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/AuctionTypeWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/CategoryTabWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/RarityWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/SliderWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/SortWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemRarityBackgrounds.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockItemRarity.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/AbstractCustomHypixelGUI.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/AbstractPopupScreen.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/auction_type_widget/all.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/auction_type_widget/auctions.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/auction_type_widget/back.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/auction_type_widget/bin.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/auction_type_widget/hover.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/browser/background.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/browser/background_view.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/rarity_widget/background.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/rarity_widget/hover.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/sort_widget/back.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/sort_widget/high.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/sort_widget/hover.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/sort_widget/low.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/sort_widget/rand.png
  src/main/resources/assets/skyblocker/textures/gui/auctions_gui/sort_widget/soon.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/down_arrow_even.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/up_arrow_even.png
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please, high priority, bleeding edge

#624 Allow drop in dungeon option for locked slots
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/HotbarSlotLock.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please, bleeding edge

#646 Add fishing fetures
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/RenderFishMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/FishingHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please, bleeding edge

#648 Fix highlighting empty slot
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionBrowserScreen.java
Labels: bug, merge me please, high priority

#640 Dungeon Crypts Message
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, bleeding edge

#649 Add color interpolation for Dwarven Hud
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Colors.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudCommsWidget.java
Labels: merge me please, bleeding edge

#650 Fix has highest tier
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/AccessoriesHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
Labels: bug, merge me please, bleeding edge

#653 Metal detector helper
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DwarvenMinesCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/AuctionTypeWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/SortWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/MetalDetector.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/dwarven/MetalDetectorTest.java
Labels: new feature, merge me please

#636 Update ItemCooldowns.java
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
  src/main/java/de/hysky/skyblocker/utils/ProfileUtils.java
Labels: merge me please, bleeding edge

#652 Prevent teammates glow during Livid
  src/main/java/de/hysky/skyblocker/mixin/WorldRendererMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonBoss.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
Labels: new feature, merge me please, bleeding edge

#661 Java 21 CI
  .github/workflows/beta.yml
  .github/workflows/buildrelease.yml
Labels: compatibility, merge me please

#662 Fix item repository update
  src/main/java/de/hysky/skyblocker/utils/FileUtils.java
Labels: bug, merge me please

#654 Fancier bars
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/mixin/WindowMixin.java
  src/main/java/de/hysky/skyblocker/mixin/accessor/DrawContextInvoker.java
  src/main/java/de/hysky/skyblocker/skyblock/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/EditBidPopup.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/BarPositioner.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/EditBarColorPopup.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/EditBarWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBar.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBarsConfigScreen.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/AbstractPopupScreen.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/bars.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/bar_back.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/bar_back.png.mcmeta
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/bar_fill.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/bar_fill.png.mcmeta
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/icons/defense.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/icons/experience.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/icons/health.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/icons/intelligence.png
  src/main/resources/skyblocker.mixins.json
Labels: merge me please, bleeding edge

#660 Fix delete shortcut
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigScreen.java
Labels: bug, merge me please

#663 Fix update repository
  src/main/java/de/hysky/skyblocker/utils/FileUtils.java
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: bug, merge me please, high priority

#664 fix metal detector braking when trying to use it in a second lobby
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/MetalDetector.java
Labels: bug, merge me please

#635 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/it_it.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/ko_kr.json
  src/main/resources/assets/skyblocker/lang/nb_no.json
  src/main/resources/assets/skyblocker/lang/nl_nl.json
  src/main/resources/assets/skyblocker/lang/nn_no.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#665 update mod to 1.20.0
  CHANGELOG.md
  FEATURES.md
  MRREADME.md
  README.md
  gradle.properties
Labels: merge me please

#666 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#668 fix garden icons and clamp the progress bar
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/ProgressComponent.java
Labels: bug, merge me please

#667 fix and things for end hud
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/LocationsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EndHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/end/TheEnd.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#672 Update mod to 1.20.1
  .github/workflows/beta.yml
  .github/workflows/webhook_translate.yml
  CHANGELOG.md
  gradle.properties
  src/main/resources/fabric.mod.json
Labels: merge me please

#673 Fix item repo NPE
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
Labels: bug, crash, merge me please, high priority

#674 updata
  CHANGELOG.md
  gradle.properties
Labels: merge me please

#675 Fixes and things
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenProviderMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreenHandler.java
Labels: bug, reviews needed, tester needed
