Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-05, with the labels that each got.

#698 Nothing to see here, part 2
  src/main/java/de/hysky/skyblocker/utils/Constants.java
  src/test/java/de/hysky/skyblocker/utils/ConstantsTest.java
Labels: new feature, merge me please

#699 ???
  src/main/java/de/hysky/skyblocker/SkyblockerScreen.java
  src/main/resources/assets/skyblocker/icons.png
Labels: new feature, merge me please

#688 Add a way to show all ordered waypoints at once
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#692 Adds Mines Slayer starter commission and deprecates the classic hud for removal
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
Labels: bug, documentation, merge me please

#693 Fix accessories helper not working with only 1 accessory bag page
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/AccessoriesHelper.java
Labels: bug, merge me please

#701 Config Data Fixer
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/java/de/hysky/skyblocker/config/categories/QuickNavigationCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/QuickNavigationConfig.java
  src/main/java/de/hysky/skyblocker/config/datafixer/ConfigDataFixer.java
  src/main/java/de/hysky/skyblocker/config/datafixer/ConfigFix1.java
  src/main/java/de/hysky/skyblocker/config/datafixer/ConfigSchema.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNav.java
  src/main/java/de/hysky/skyblocker/utils/datafixer/JsonHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/config/datafixer/ConfigDataFixerTest.java
  src/test/resources/assets/skyblocker/config/skyblocker-v1.json
  src/test/resources/assets/skyblocker/config/skyblocker-v2.json
Labels: merge me please, high priority, bleeding edge

#689 Fix quite important AH bug
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionViewScreen.java
Labels: bug, merge me please, high priority, bleeding edge

#690 add waypoints for commissions in dwarven mines and glacite.
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CommissionLabels.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsHud.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsWaypoint.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/MiningLocationLabel.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, bleeding edge

#711 Add line smoothener
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
Labels: merge me please, bleeding edge

#686 Sign calculator
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/SignEditScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/EditBidPopup.java
  src/main/java/de/hysky/skyblocker/skyblock/calculators/CalculatorCommand.java
  src/main/java/de/hysky/skyblocker/skyblock/calculators/SignCalculator.java
  src/main/java/de/hysky/skyblocker/utils/Calculator.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
  src/test/java/de/hysky/skyblocker/utils/CalculatorTest.java
Labels: new feature, merge me please, bleeding edge

#710 Block Incorrect Terminal Clicks
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/ColorTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/LightsOnTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/OrderTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/StartsWithTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/TerminalSolver.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolver.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, reviews needed, bleeding edge

#702 Hide Soulweaver Skulls
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/EntityRenderDispatcherMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, reviews needed, bleeding edge

#696 Add compact damage
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/CompactDamage.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorAnimatedDyes.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#712 Clarify the regex in CompactDamage
  src/main/java/de/hysky/skyblocker/skyblock/CompactDamage.java
Labels: merge me please

#715 Internal Staging
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/java/de/hysky/skyblocker/config/categories/ForagingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/ForagingConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/foraging/ModernForagingIsland.java
  src/main/java/de/hysky/skyblocker/utils/Location.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#716 Add LOCATION_CHANGE event, fired upon parsing /locraw
  src/main/java/de/hysky/skyblocker/events/SkyblockEvents.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: merge me please

#643 Quick Nav Refactor and Clean Up, 2 Extra Tabs, Config Version 3, Config Data Fixer Refactor, Debug Dump Hovered Item Tool
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/java/de/hysky/skyblocker/config/categories/QuickNavigationCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/QuickNavigationConfig.java
  src/main/java/de/hysky/skyblocker/config/datafixer/ConfigDataFix.java
  src/main/java/de/hysky/skyblocker/config/datafixer/ConfigDataFixer.java
  src/main/java/de/hysky/skyblocker/config/datafixer/ConfigFix1.java
  src/main/java/de/hysky/skyblocker/config/datafixer/ConfigFix2QuickNav.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixins/accessors/HandledScreenAccessor.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNav.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/config/datafixer/ConfigDataFixerTest.java
  src/test/resources/assets/skyblocker/config/skyblocker-v3.json
Labels: good first issue, merge me please, bleeding edge

#704 Fancy status bars bits and pieces
  src/main/java/de/hysky/skyblocker/mixins/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/BarPositioner.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBar.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBarsConfigScreen.java
Labels: bug, merge me please, bleeding edge

#705 Migrate ThreeWeirdos to DungeonPuzzle and highlight chest
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/DungeonPuzzle.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/ThreeWeirdos.java
  src/main/java/de/hysky/skyblocker/utils/Resettable.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatMessageListener.java
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/ThreeWeirdosTest.java
  src/test/java/de/hysky/skyblocker/utils/chat/ChatPatternListenerTest.java
Labels: merge me please, bleeding edge

#720 fix bugs
  src/main/java/de/hysky/skyblocker/skyblock/calculators/SignCalculator.java
  src/main/java/de/hysky/skyblocker/utils/Calculator.java
Labels: bug, merge me please

#722 Make TerminalSolver interface & ExperimentSolver class sealed
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/ColorTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/LightsOnTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/OrderTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/StartsWithTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/TerminalSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/ChronomatronSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/ExperimentSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/SuperpairsSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/UltrasequencerSolver.java
Labels: merge me please

#683 Add chocolate factory helper
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/CompactDamage.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/TimeTowerReminder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/utils/ColorUtils.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/RegexUtils.java
  src/main/java/de/hysky/skyblocker/utils/SkyblockTime.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, bleeding edge

#703 Glacite Overlay (Oops)
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/mixins/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/GlaciteColdOverlay.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, good first issue, merge me please

#719 chat rules - fix bugs + refactor
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRule.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRuleConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesConfigListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesHandler.java
Labels: bug, merge me please

#725 Remove extended quicknav string
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#730 Debug class? More like Rebug class lmao gottem
  src/main/java/de/hysky/skyblocker/debug/Debug.java
Labels: bug, crash, merge me please

#734 Update chocolate factory for chocolate factory 2
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
Labels: merge me please

#729 Fix egg found message being sent twice
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/TimeTowerReminder.java
Labels: bug, merge me please, bleeding edge
