Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-06, with the labels that each got.

#732 Fix entrance (0) not being in the map
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
Labels: bug, reviews needed, merge me please

#736 VisitorHelper Tweak
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
Labels: new feature, good first issue, merge me please

#739 Improve search overlay
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/OverlayScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#691 Calendar Event Notifications
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/java/de/hysky/skyblocker/config/categories/EventNotificationsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/EventNotificationsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/CategoryTabWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/events/EventNotifications.java
  src/main/java/de/hysky/skyblocker/skyblock/events/EventToast.java
  src/main/java/de/hysky/skyblocker/skyblock/events/JacobEventToast.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemListTab.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/SearchResultsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/UpcomingEventsTab.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/JacobsContestWidget.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/config/DurationController.java
  src/main/java/de/hysky/skyblocker/utils/config/DurationControllerWidget.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/SideTabButtonWidget.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/sprites/notification.png
  src/main/resources/assets/skyblocker/textures/gui/sprites/notification.png.mcmeta
Labels: new feature, merge me please, bleeding edge

#685 Farming hud improvements
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CroesusProfit.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/LowerSensitivity.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: bug, new feature, merge me please, bleeding edge

#735 Tooltip refactors
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/injected/SkyblockerStack.java
  src/main/java/de/hysky/skyblocker/mixins/DrawContextMixin.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixins/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/mixins/accessors/HandledScreenAccessor.java
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/java/de/hysky/skyblocker/skyblock/TeleportOverlay.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionBrowserScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotText.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/TextPosition.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/AttributeShardAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CatacombsLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EnchantmentLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/MinionLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PetLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PrehistoricEggAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/RancherBootsSpeedAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkillLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkyblockLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/AccessoriesHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/CompactorDeletorPreview.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ExoticTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/AccessoryTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/AvgBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/BazaarPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/ColorTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/DungeonQualityTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/LBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/LineSmoothener.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/MotesTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/MuseumTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/NpcPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/ObtainedDateTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/SupercraftReminder.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ResultButtonWidget.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/RomanNumerals.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/fabric.mod.json
  src/test/java/de/hysky/skyblocker/utils/ItemUtilsTest.java
  src/test/java/de/hysky/skyblocker/utils/RomanNumeralsTest.java
Labels: new feature, merge me please, high priority

#755 Misc Changes
  gradle.properties
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/resources/fabric.mod.json
Labels: bug, merge me please

#763 Add event notifications criterion
  src/main/java/de/hysky/skyblocker/config/categories/EventNotificationsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/EventNotificationsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/events/EventNotifications.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#771 Fix egg finder sharing nonsense
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
Labels: bug, merge me please

#777 update mod to 1.21.0
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBarsConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/AttributeShardAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CatacombsLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CollectionAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EnchantmentLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EssenceShopAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/MinionLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PetLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PotionLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PowerStonesGuideAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PrehistoricEggAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/RancherBootsSpeedAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkillLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkyblockLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/StatsTuningAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/YourEssenceAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/resources/fabric.mod.json
Labels: reviews needed

#700 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/it_it.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/ko_kr.json
  src/main/resources/assets/skyblocker/lang/nb_no.json
  src/main/resources/assets/skyblocker/lang/nn_no.json
  src/main/resources/assets/skyblocker/lang/pl_pl.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#794 1.21.0 for 1.21.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
  CHANGELOG.md
  src/main/java/de/hysky/skyblocker/mixins/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/utils/Http.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.accesswidener
Labels: reviews needed

#790 Fix Golden Stray Rabbits not getting highlighted
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
Labels: bug, merge me please, bleeding edge, small change

#809 Change OptionalInt costs to OptionalLong
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
Labels: bug, crash, merge me please, small change

#738 Nucleus waypoints
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/NucleusWaypoints.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, bleeding edge

#752 Refactor and add more tips
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/SkyblockerScreen.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/Tips.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please, bleeding edge

#797 Add completed commission highlight
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CommissionHighlight.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please, bleeding edge, small change

#810 Remove the development environment branch from the isInLocation methods
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: merge me please, small change
