Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-07, with the labels that each got.

#814 Fix wrong icon being shown when the player has enough gems to instantly upgrade
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CommunityShopAdder.java
Labels: bug, merge me please, bleeding edge, small change

#747 Dojo helper
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/CrimsonIsleCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/CrimsonIsleConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/ClientWorldMixin.java
  src/main/java/de/hysky/skyblocker/mixins/PingMeasurerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/ControlTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/DisciplineTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/DojoManager.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/ForceTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/MasteryTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/StaminaTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/SwiftnessTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/TenacityTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please, bleeding edge

#748 Jerry timer
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/mayors/JerryTimer.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, bleeding edge, small change

#768 Migrate to setup gradle
  .github/workflows/beta.yml
Labels: merge me please, bleeding edge, small change

#718 Equipment in inventory
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/events/SkyblockEvents.java
  src/main/java/de/hysky/skyblocker/mixins/GenericContainerScreenHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/InventoryScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixins/MinecraftClientMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockInventoryScreen.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/sprites/equipment/empty_icon.png
Labels: new feature, merge me please, bleeding edge

#751 Schedule mayor cache ticking to the next year rather than every 20 mins
  src/main/java/de/hysky/skyblocker/utils/Http.java
  src/main/java/de/hysky/skyblocker/utils/SkyblockTime.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: bug, merge me please, bleeding edge

#782 Multiply npc price tooltip by the amount of items in the sack
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/NpcPriceTooltip.java
Labels: bug, merge me please, bleeding edge, small change

#817 Fix PetLevelAdder working incorrectly in the sea creatures guide
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PetLevelAdder.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: bug, merge me please, bleeding edge, small change

#821 Fix discord announcement not including minecraft version
  build.gradle
Labels: bug, merge me please

#831 Fix control test helper for dojo
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/ControlTestHelper.java
Labels: bug, merge me please, small change

#829 Locraw remover 9000
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/Reparty.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/fabric.mod.json
Labels: merge me please, high priority, bleeding edge, small change

#724 Simon Says Solver & Lights On Solver
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientWorldMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/device/LightsOn.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/device/SimonSays.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, bleeding edge

#833 Aaron's Mod compatibility for profile viewer
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemStackBuilder.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/collections/GenericCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/itemLoaders/ItemLoader.java
  src/main/java/de/hysky/skyblocker/utils/TextTransformer.java
Labels: compatibility, merge me please

#836 Item Protection Enhancements
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
Labels: merge me please, small change

#838 Workaround "fake" transparent pixels
  src/main/java/de/hysky/skyblocker/mixins/PlayerSkinTextureMixin.java
Labels: bug, merge me please, small change

#839 Fix recipe book search being case sensitive
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/SearchResultsWidget.java
Labels: bug, merge me please, small change

#728 Bazaar Helper
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/bazaar/BazaarHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/bazaar/ReorderHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/filters/SimpleChatFilter.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotText.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatPatternListener.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolver.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, bleeding edge

#804 Change colo(u)r for max collections and skills slot text
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CollectionAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkillLevelAdder.java
Labels: merge me please, bleeding edge, small change

#834 Add some custom command argument types
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorAnimatedDyes.java
  src/main/java/de/hysky/skyblocker/skyblock/item/CustomArmorDyeColors.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/MythologicalRitual.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java
  src/main/java/de/hysky/skyblocker/utils/command/argumenttypes/EggTypeArgumentType.java
  src/main/java/de/hysky/skyblocker/utils/command/argumenttypes/blockpos/ClientBlockPosArgumentType.java
  src/main/java/de/hysky/skyblocker/utils/command/argumenttypes/blockpos/ClientPosArgument.java
  src/main/java/de/hysky/skyblocker/utils/command/argumenttypes/blockpos/DefaultClientPosArgument.java
  src/main/java/de/hysky/skyblocker/utils/command/argumenttypes/blockpos/LookingClientPosArgument.java
  src/main/java/de/hysky/skyblocker/utils/command/argumenttypes/color/ColorArgumentType.java
  src/main/java/de/hysky/skyblocker/utils/command/argumenttypes/color/HexColorArgumentType.java
  src/main/java/de/hysky/skyblocker/utils/command/argumenttypes/color/RgbColorArgumentType.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.accesswidener
Labels: bug, merge me please

#840 Fix quicknav buttons 8, 9 and 12 having empty string as ui title
  src/main/java/de/hysky/skyblocker/config/configs/QuickNavigationConfig.java
Labels: bug, merge me please, small change

#842 Fix result text displaying weirdly when its too long in the recipe book
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/SearchResultsWidget.java
Labels: bug, merge me please, small change

#843 Fix dungeon secret widget spamming logs
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonSecretWidget.java
Labels: bug, merge me please, small change

#841 Some fixes and some opinionated changes for the en_us lang file
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#737 EssenceShopPrice feature
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipInfoType.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EssenceShopPrice.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#765 make all formatting use static instances of numberformat using US locale
  src/main/java/de/hysky/skyblocker/skyblock/calculators/CalculatorCommand.java
  src/main/java/de/hysky/skyblocker/skyblock/calculators/SignCalculator.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EndHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
Labels: merge me please

#844 Update Attribute Short Names
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/AttributeShardAdder.java
Labels: bug, merge me please, small change

#853 Fix Memory Leak
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemStackBuilder.java
Labels: bug, merge me please, high priority

#848 Fix rare npe in OrderTerminal
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/OrderTerminal.java
Labels: bug, crash, merge me please, small change

#852 Fix inconsistency with Hypixel's inconsistencies
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudPowderWidget.java
Labels: merge me please, small change

#791 Improve mining waypoint
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/PlayerListHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsHud.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationsManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsWaypoint.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/MetalDetector.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/MiningLocationLabel.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/WishingCompassSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/PlayerListMgr.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsLocationManagerTest.java
  src/test/java/de/hysky/skyblocker/skyblock/dwarven/WishingCompassSolverTest.java
Labels: new feature, merge me please, bleeding edge

#863 Make ChocolateFactorySolver a singleton to fix tooltip not working
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
Labels: bug, merge me please, small change

#726 use bounding box instead of block size
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/device/SimonSays.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/ThreeWeirdos.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/TicTacToe.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/boulder/Boulder.java
  src/main/java/de/hysky/skyblocker/utils/Boxes.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
Labels: merge me please

#812 emi/rei, Quicknav, livid and nukekubi head (eman boss head) fix
  gradle.properties
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/compatibility/emi/SkyblockerEMIPlugin.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobBoundingBoxes.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CollectionAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please, bleeding edge, backport me

#851 Fix empty categories being checked
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/WaypointsListWidget.java
Labels: bug, merge me please, small change, backport me

#854 Move to Mod API for isOnSkyblock detection
  src/main/java/de/hysky/skyblocker/events/SkyblockEvents.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: bug, merge me please, backport me

#792 Bazaar Lookup/Misc Options
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/ConfigUtils.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/MiscCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/bazaar/BazaarHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#856 Option to increase fog radius when in the Crimson Isles
  src/main/java/de/hysky/skyblocker/config/categories/CrimsonIsleCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/CrimsonIsleConfig.java
  src/main/java/de/hysky/skyblocker/mixins/BackgroundRendererMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, good first issue, merge me please

#868 Fix slot text not working on favorited pets
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotText.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CatacombsLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CollectionAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CommunityShopAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EnchantmentLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EssenceShopAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/MinionLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PetLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PotionLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PowerStonesGuideAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PrehistoricEggAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/RancherBootsSpeedAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkillLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkyblockLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/StatsTuningAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/YourEssenceAdder.java
Labels: bug, merge me please, small change, backport me

#871 Center quick nav buttons in bigger UIs
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
Labels: compatibility, merge me please

#827 Add slot text to Rabbit levels in the Chocolate Factory
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/utils/RomanNumerals.java
Labels: good first issue, merge me please, bleeding edge

#835 Tooltip Tweaks
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/ColorTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/ObtainedDateTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/TrueHexDisplay.java
  src/main/java/de/hysky/skyblocker/utils/Constants.java
Labels: new feature, merge me please

#867 Clean up id mess and add tests
  src/main/java/de/hysky/skyblocker/injected/SkyblockerStack.java
  src/main/java/de/hysky/skyblocker/mixins/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/java/de/hysky/skyblocker/skyblock/PetCache.java
  src/main/java/de/hysky/skyblocker/skyblock/TeleportOverlay.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionBrowserScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/dojo/DisciplineTestHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CroesusProfit.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/WishingCompassSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PrehistoricEggAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/RancherBootsSpeedAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/AvgBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/BazaarPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/CraftPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/LBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/MotesTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/NpcPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/test/java/de/hysky/skyblocker/utils/ItemUtilsTest.java
Labels: bug, merge me please, high priority, backport me

#882 Fix Roman Numeral parsing crash
  src/main/java/de/hysky/skyblocker/utils/RomanNumerals.java
Labels: bug, crash, merge me please
