Repository SkyblockerMod/Skyblocker, pull requests merged in 2024-01, with the labels that each got.

#465 Durability Fix
  src/main/java/de/hysky/skyblocker/mixin/accessor/ItemStackAccessor.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/resources/skyblocker.mixins.json
  src/test/java/de/hysky/skyblocker/utils/ItemUtilsTest.java
Labels: merge me please

#466 Migrate to Fabric Api ClientPlayerBlockBreakEvents
  gradle.properties
  src/main/java/de/hysky/skyblocker/events/ClientPlayerBlockBreakEvent.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerInteractionManagerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
  src/main/resources/fabric.mod.json
  src/main/resources/skyblocker.mixins.json
Labels: merge me please

#467 Waterboard Solver
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/CreeperBeams.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/DungeonBlaze.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/DungeonPuzzle.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/TicTacToe.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/waterboard/Cell.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/waterboard/Switch.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/waterboard/Waterboard.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/MythologicalRitual.java
  src/main/java/de/hysky/skyblocker/utils/Tickable.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/Waypoint.java
Labels: new feature, merge me please

#468 Correct Transparent Skin Pixels
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/PlayerSkinTextureMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#469 Add Dungeon Score
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/utils/scheduler/MessageScheduler.java
  src/main/java/de/hysky/skyblocker/utils/scheduler/Scheduler.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature

#472 Two fixes
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/FireSaleWidget.java
Labels: bug

#473 Audit Mixins
  src/test/java/de/hysky/skyblocker/MixinsTest.java
Labels: merge me please

#474 Fix broken quiz question
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/Trivia.java
Labels: bug, merge me please

#475 Toggle Sky Mall Filter
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/MessageFilterCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/filters/ToggleSkyMallFilter.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatMessageListener.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#476 Add Waterboard toggle
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/waterboard/Waterboard.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#479 Use vanilla translations
  src/main/java/de/hysky/skyblocker/utils/BasePlaceholderScreen.java
  src/main/java/de/hysky/skyblocker/utils/JoinWorldPlaceholderScreen.java
  src/main/java/de/hysky/skyblocker/utils/ReconfiguringPlaceholderScreen.java
Labels: merge me please

#480 Add dungeon score title and sound
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#482 Add livid color title
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#477 Fix Skin Transparency applying to player skins
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/mixin/PlayerSkinTextureMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/PlayerHeadHashCache.java
Labels: bug, reviews needed

#483 Support new epoch milli obtained timestamps
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/test/java/de/hysky/skyblocker/utils/ItemUtilsTest.java
Labels: bug, reviews needed

#471 Add sync when clearing matchState
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/Room.java
Labels: bug, merge me please, wip

#484 Loom 1.5 & JGit 6.8.0
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/mixin/DataTrackerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/DrawContextMixin.java
  src/main/java/de/hysky/skyblocker/mixin/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/mixin/LeverBlockMixin.java
  src/main/java/de/hysky/skyblocker/mixin/MinecraftClientMixin.java
  src/main/java/de/hysky/skyblocker/mixin/PlayerListHudMixin.java
  src/main/java/de/hysky/skyblocker/mixin/PlayerSkinTextureMixin.java
  src/main/resources/fabric.mod.json
Labels: reviews needed

#485 Fix tips triggering too much
  src/main/java/de/hysky/skyblocker/skyblock/Tips.java
Labels: bug, merge me please

#452 add new built-in texture pack for recolored textures in dungeons
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonTextures.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/ScreenMaster.java
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/blockstates/tripwire.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_attached_n.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_attached_ne.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_attached_ns.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_attached_nse.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_attached_nsew.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_hook.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_hook_attached.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_hook_attached_on.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_n.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_ne.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_ns.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_nse.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_nsew.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_powered_n.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_powered_ne.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_powered_ns.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_powered_nse.json
  src/main/resources/resourcepacks/recolored_dungeon_items/assets/minecraft/models/block/tripwire_powered_nsew.json
  src/main/resources/resourcepacks/recolored_dungeon_items/pack.mcmeta
Labels: new feature, merge me please

#488 Add Hypixel's colouring to Dwarven Mines HUD.
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/DwarvenHud.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Colors.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/hud/HudCommsWidget.java
Labels: new feature, merge me please

#490 1.20.4 & 1.20.2 only issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
Labels: bug, merge me please

#492 Update top aligned pack.mcmeta
  src/main/resources/resourcepacks/top_aligned/pack.mcmeta
Labels: bug, merge me please

#496 More tips
  src/main/java/de/hysky/skyblocker/skyblock/Tips.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#487 Add a custom GUI for the Party Finder in dungeons
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/mixin/GenericContainerScreenHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/HandledScreenProviderMixin.java
  src/main/java/de/hysky/skyblocker/mixin/accessor/SkullBlockEntityAccessor.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/FinderSettingsContainer.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/OptionDropdownWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/PartyEntry.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/PartyEntryListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/PartyFinderScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/RangedValueWidget.java
  src/main/resources/assets/skyblocker/dungeons/catacombs/floorskulls.json
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/party_card.png
  src/main/resources/assets/skyblocker/textures/gui/party_card_hover.png
  src/main/resources/skyblocker.accesswidener
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#493 Dungeons improvements.
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, new feature, merge me please

#501 Changed tips from true random to non-repeating random
  src/main/java/de/hysky/skyblocker/skyblock/Tips.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#504 Tic Tac Toe Refactor
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/CreeperBeams.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/DungeonBlaze.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/TicTacToe.java
  src/main/java/de/hysky/skyblocker/utils/tictactoe/TicTacToeUtils.java
Labels: merge me please

#506 YACL 3.3.2 (Critical update)
  gradle.properties
  src/main/resources/fabric.mod.json
Labels: bug, merge me please

#507 Handle rate limits
  src/main/java/de/hysky/skyblocker/utils/ApiUtils.java
  src/main/java/de/hysky/skyblocker/utils/Http.java
Labels: bug, merge me please

#508 Fix fishing timer appearing outside Skyblock.
  src/main/java/de/hysky/skyblocker/skyblock/FishingHelper.java
Labels: bug, merge me please

#500 Add dungeon score calculation on client-side
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/MessageFilterCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixin/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonMap.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonMapConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScoreHUD.java
  src/main/java/de/hysky/skyblocker/skyblock/filters/DeathFilter.java
  src/main/java/de/hysky/skyblocker/skyblock/filters/MimicFilter.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatMessageListener.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#509 Texture size, draw and transparency
  src/main/java/de/hysky/skyblocker/mixin/InGameHudMixin.java
  src/main/resources/assets/skyblocker/textures/gui/slot_lock.png
Labels: merge me please

#510 Fix Active Effects widget
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/EffectWidget.java
Labels: bug, merge me please

#505 Make fancy_slot_lock.png
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixin/InGameHudMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/fancy_slot_lock.png
Labels: new feature, merge me please

#513 Lowercase party and search strings to ignore case
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/PartyEntryListWidget.java
Labels: bug, merge me please

#512 Add anita's talisman fortune boost indicator next to the relevant crop
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/JacobsContestWidget.java
Labels: new feature, merge me please

#502 Enderman Slayer Utilities
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfig.java
  src/main/java/de/hysky/skyblocker/config/categories/SlayersCategory.java
  src/main/java/de/hysky/skyblocker/mixin/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/end/BeaconHighlighter.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#516 Update mod to 1.17.0
  CHANGELOG.md
  FEATURES.md
  MRREADME.md
  README.md
  gradle.properties
Labels: merge me please
