Repository SkyblockerMod/Skyblocker, pull requests merged in 2025-02, with the labels that each got.

#1155 Add raffle task highlighter
  src/main/java/de/hysky/skyblocker/skyblock/RaffleTaskHighlight.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
Labels: new feature, merge me please, small change

#1150 Properly empty layout in AuctionViewScreen
  src/main/java/de/hysky/skyblocker/skyblock/auction/AuctionViewScreen.java
Labels: bug, merge me please

#1149 Pet Widget Fix
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/PetWidget.java
Labels: bug, merge me please

#1148 Update Combofilter
  src/main/java/de/hysky/skyblocker/skyblock/chat/filters/ComboFilter.java
  src/test/java/de/hysky/skyblocker/skyblock/chat/filters/ComboFilterTest.java
Labels: bug, merge me please

#1157 Upate mod to 5.0.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
Labels: merge me please

#1079 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/id_id.json
  src/main/resources/assets/skyblocker/lang/it_it.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/ko_kr.json
  src/main/resources/assets/skyblocker/lang/nl_nl.json
  src/main/resources/assets/skyblocker/lang/nn_no.json
  src/main/resources/assets/skyblocker/lang/pl_pl.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/vi_vn.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#1161 Fix incorrect translation for SkillLevelAdder
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkillLevelAdder.java
Labels: bug, merge me please, small change

#1171 fix right icon not rendering lol
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBar.java
Labels: merge me please

#1108 Add seen waypoint
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EnderNodes.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/SeenWaypoint.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/Waypoint.java
Labels: merge me please

#1121 Fix recipe book crashes
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/RecipeTab.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingTab.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/UpcomingEventsTab.java
Labels: crash, merge me please

#1151 Formatters
  build.gradle
  src/main/java/de/hysky/skyblocker/utils/Formatters.java
  src/test/java/de/hysky/skyblocker/utils/FormattersTest.java
Labels: merge me please, small change

#1162 Fix the way jacob's contest widget is parsed and displayed
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/JacobsContestWidget.java
Labels: bug, merge me please

#1168 Boosted Pets Background Rarity
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemRarityBackgrounds.java
Labels: bug, merge me please

#1169 Fixed Vampire Features not working
  src/main/java/de/hysky/skyblocker/config/configs/SlayersConfig.java
  src/main/java/de/hysky/skyblocker/events/SkyblockEvents.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/SlayerManager.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/demonlord/FirePillarAnnouncer.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/vampire/ManiaIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/vampire/StakeIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/vampire/TwinClawsIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/voidgloom/BeaconHighlighter.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/voidgloom/LazerTimer.java
  src/main/java/de/hysky/skyblocker/utils/Area.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: bug, question, merge me please

#1127 Add "Swing On Abilities"
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayerInteractionManagerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/SwingAnimation.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#1132 move disabled slots out of the way
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockCraftingTableScreenHandler.java
Labels: merge me please, small change

#1152 Corpse profit tracker
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/config/screens/powdertracker/PowderFilterConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CorpseFinder.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CorpseType.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/AbstractProfitTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/PowderMiningTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/corpse/CorpseList.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/corpse/CorpseLoot.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/corpse/CorpseProfitScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/corpse/CorpseProfitTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/corpse/Reward.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/corpse/RewardList.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1176 Fix npc price tooltip crash with cookie's mod
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/NpcPriceTooltip.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/TextUtils.java
Labels: bug, merge me please
