Repository SkyblockerMod/Skyblocker, pull requests merged in 2025-06, with the labels that each got.

#1269 Add ingame fishing hook timer display
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHookDisplayHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, good first issue, merge me please

#1292 fix jacobs event toast being too small in certain languages
  src/main/java/de/hysky/skyblocker/skyblock/events/EventToast.java
  src/main/java/de/hysky/skyblocker/skyblock/events/JacobEventToast.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1259 Refresh inventory search highlight when slot changes
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/ScreenHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/InventorySearch.java
  src/main/resources/skyblocker.mixins.json
Labels: merge me please, small change

#1296 fix wishing compass solver distance
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CrystalsChestHighlighter.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/WishingCompassSolver.java
Labels: bug, merge me please

#1297 Show all warp autocompletes for Bingo profiles.
  src/main/java/de/hysky/skyblocker/skyblock/WarpAutocomplete.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
Labels: merge me please

#1298 more status bar anchors
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/BarPositioner.java
Labels: new feature, merge me please

#1301 Fix npc price tooltip to include price * itemCount
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/BazaarPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/CraftPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EstimatedItemValueTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/NpcPriceTooltip.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/networth/NetworthCalculator.java
Labels: bug, merge me please, small change

#1306 Improve scheduler thread safety to prevent crashes
  src/main/java/de/hysky/skyblocker/utils/scheduler/Scheduler.java
Labels: reviews needed, crash

#1310 Verify Json Files
  src/test/java/de/hysky/skyblocker/VerifyJsonTest.java
Labels: merge me please

#1293 kitty yay
  src/main/java/de/hysky/skyblocker/config/categories/MiscCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiscConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/CatPicture.java
  src/main/resources/assets/skyblocker/textures/cat.png
Labels: new feature, merge me please

#1294 Fixed a bug where the fishing widget would not update
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/hud/SlayerHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/config/preview/PreviewTab.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/ScreenBuilder.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/WidgetManager.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/PlayerListManager.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ComponentBasedWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/HudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/TabHudWidget.java
Labels: merge me please

#1295 Item pickup Widget
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ScreenHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/ItemPickupWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ComponentBasedWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/Components.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1307 Bar changes
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/ConfigUtils.java
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/SmoothAOTE.java
  src/main/java/de/hysky/skyblocker/skyblock/StatusBarTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBar.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBarType.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/StatusBarTrackerTest.java
Labels: merge me please

#1314 Remove hover text on chat waypoint suggestion message
  src/main/java/de/hysky/skyblocker/skyblock/barn/TreasureHunter.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatPositionShare.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1316 Fix customize button not moving when recipe book is toggled + refactor
  src/main/java/de/hysky/skyblocker/injected/RecipeBookHolder.java
  src/main/java/de/hysky/skyblocker/mixins/InventoryScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/CustomizeArmorScreen.java
Labels: merge me please

#1329 Clarify Search Overlay translation for Bazaar/AH
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1332 space
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1325 Add waypoints to forest nodes
  src/main/java/de/hysky/skyblocker/config/categories/ForagingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/ForagingConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/galatea/ForestNodes.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1338 Update EnchantmentLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EnchantmentLevelAdder.java
Labels: merge me please

#1271 Garden fixes
  src/main/java/de/hysky/skyblocker/config/categories/FarmingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/FarmingConfig.java
  src/main/java/de/hysky/skyblocker/mixins/InventoryScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ComponentBasedWidget.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1348 Add periods to sentences
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1356 Increase Chat Rule Character Limit
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRuleConfigScreen.java
Labels: merge me please

#1346 Add Deleting Items from AH/BZ Search Overlay History
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayerEntityMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/OverlayScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1340 Clean up fishing stuff
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHookDisplayHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/SeaCreature.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/SeaCreatureTracker.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#1362 fix: some tabwidget icons being incorrect
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonClass.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Ico.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ElectionWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ForgeWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ProfileWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ServerWidget.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: bug, merge me please

#1367 Adds an oxygen bar
  src/main/java/de/hysky/skyblocker/skyblock/StatusBarTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBarType.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/sprites/bars/icons/air.png
Labels: new feature, merge me please, alpha-net

#1343 update cooldown for new axe throw ability
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
Labels: merge me please, alpha-net

#1371 Add REI exclusion zone for Visitor Helper Gui
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREIClientPlugin.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
Labels: bug, merge me please

#1374 Fix dungeon entrance pos detection
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
Labels: bug, merge me please, high priority

#1376 Set the default of hideStatusEffectOverlay to true
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
Labels: merge me please, small change

#1377 Removes the Estimated Price from Bazaar Items
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EstimatedItemValueTooltip.java
Labels: merge me please

#1369 Highlights items with attributes
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/item/background/ItemBackgroundManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/background/adders/LegacyAttributeBackground.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, alpha-net

#1386 Remove deprecated space assignments from build.gradle
  build.gradle
Labels: merge me please

#1384 Fix Bobber Time widget not working after max time was exceeded
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHudWidget.java
Labels: bug, merge me please

#1158 Add collapse button to waypoint groups in Waypoints Screen
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/ColorSelectionWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/WaypointsListWidget.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ARGBTextInput.java
Labels: merge me please

#1388 update mod to 5.3.0
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
Labels: merge me please

#1416 Fix Item Pickup Widget Network Protocol Error Disconnect
  src/main/java/de/hysky/skyblocker/skyblock/ItemPickupWidget.java
Labels: merge me please

#1399 Add attribute level slot text
  src/main/java/de/hysky/skyblocker/skyblock/hunting/AttributeLevelHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/utils/container/SlotTextAdder.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1383 Fix suggestions flashing sometimes when removing history entry
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/OverlayScreen.java
Labels: bug, merge me please

#1368 Calculator improvements
  src/main/java/de/hysky/skyblocker/skyblock/calculators/CalculatorCommand.java
  src/main/java/de/hysky/skyblocker/utils/Calculator.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/utils/CalculatorTest.java
Labels: bug, merge me please

#1406 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/hu_hu.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/ko_kr.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#1436 5.4.0
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
Labels: merge me please, tester needed

#1415 Initial Sweep Overlay
  src/main/java/de/hysky/skyblocker/config/categories/ForagingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/ForagingConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/foraging/SweepOverlay.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1438 Fix ColorSelectionWidget showing on chain armor.
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/ColorSelectionWidget.java
Labels: bug, merge me please
