Repository SkyblockerMod/Skyblocker, pull requests merged in 2025-04, with the labels that each got.

#1257 Waypoints clean up and fixes
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/Waypoints.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/WaypointGroup.java
  src/test/java/de/hysky/skyblocker/utils/waypoint/WaypointsTest.java
Labels: reviews needed

#1238 Slayer crash fix
  src/main/java/de/hysky/skyblocker/skyblock/slayers/SlayerManager.java
Labels: merge me please

#1183 Fishing HUD and Notifications
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/SeaCreature.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/SeaCreatureCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/SeaCreatureTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Ico.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/Components.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1222 Update chat cords parsing to support common "X Y Z" format
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatPositionShare.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/IndividualWaypoint.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
Labels: merge me please

#1230 Code of conduct
  CODE_OF_CONDUCT.md
Labels: merge me please
