Repository SkyblockerMod/Skyblocker, pull requests merged in 2025-01, with the labels that each got.

#1065 Add powder mining tracker
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/config/screens/powdertracker/ItemTickList.java
  src/main/java/de/hysky/skyblocker/config/screens/powdertracker/PowderFilterConfigScreen.java
  src/main/java/de/hysky/skyblocker/events/ChatEvents.java
  src/main/java/de/hysky/skyblocker/events/ItemPriceUpdateEvent.java
  src/main/java/de/hysky/skyblocker/events/SkyblockEvents.java
  src/main/java/de/hysky/skyblocker/mixins/MessageHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/PowderMiningTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemPrice.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#1116 Cancel Component Update Animation
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/HeldItemRendererMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#1117 Remove unused code and change translation
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/TabHud.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please, small change

#1122 Add feature to close sign screens with the enter key
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/SignEditScreenMixin.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#960 Corpse Finder
  src/main/java/de/hysky/skyblocker/config/categories/DebugCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DebugConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CorpseFinder.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/Waypoint.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: new feature, merge me please

#1043 Per Slot Text Toggle
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SimpleSlotTextAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextMode.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/AttributeShardAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CatacombsLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CollectionAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CommunityShopAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EnchantmentLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EssenceShopAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/MinionLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PetLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PotionLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PowerStonesGuideAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PrehistoricEggAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/RancherBootsSpeedAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkillLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/SkyblockLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/StatsTuningAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/YourEssenceAdder.java
  src/main/java/de/hysky/skyblocker/utils/container/SlotTextAdder.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1102 Profiled data api
  src/main/java/de/hysky/skyblocker/config/categories/OtherLocationsCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/PetCache.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/PowderMiningTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EndHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/end/TheEnd.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemCooldowns.java
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/AccessoriesHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/SlayerTimer.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ComponentBasedWidget.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/profile/ProfiledData.java
Labels: reviews needed

#1119 ItemList Changes
  src/main/java/de/hysky/skyblocker/skyblock/Tips.java
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemRarityBackgrounds.java
  src/main/java/de/hysky/skyblocker/skyblock/item/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/FilterOption.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/RecipeAreaDisplay.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingRecipeResults.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockCraftingTab.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeResultButton.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/UpcomingEventsTab.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/CyclingTextureWidget.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/textures/gui/filter/all.png
  src/main/resources/assets/skyblocker/textures/gui/filter/entities.png
  src/main/resources/assets/skyblocker/textures/gui/filter/items.png
  src/main/resources/assets/skyblocker/textures/gui/filter/mayors.png
  src/main/resources/assets/skyblocker/textures/gui/filter/npcs.png
Labels: merge me please

#1123 Dynamic ProgressComponent text color
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/ProgressComponent.java
  src/main/java/de/hysky/skyblocker/utils/ColorUtils.java
Labels: merge me please

#1129 Fix config not loading properly
  gradle.properties
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
Labels: merge me please

#1120 Random fixes
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemPrice.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/collections/GenericCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
  src/main/java/de/hysky/skyblocker/utils/BazaarProduct.java
  src/main/java/de/hysky/skyblocker/utils/RomanNumerals.java
  src/test/java/de/hysky/skyblocker/utils/RomanNumeralsTest.java
Labels: merge me please

#1124 Carnival Helpers
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/carnival/CatchAFish.java
  src/main/java/de/hysky/skyblocker/skyblock/carnival/ChivalrousCarnival.java
  src/main/java/de/hysky/skyblocker/skyblock/carnival/ZombieShootout.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/java/de/hysky/skyblocker/utils/Area.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1126 garden plots fixes
  src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeBookWidget.java
Labels: bug, crash, merge me please

#1128 Tab hud additions
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonPlayerManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretsTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/WishingCompassSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/TabHud.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/config/WidgetsConfigurationScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/config/preview/PreviewTab.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/ScreenBuilder.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/ScreenMaster.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/PlayerListManager.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/CommsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ComponentBasedWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonBuffWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonDeathWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonDownedWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonPlayerWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonPuzzleWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonSecretWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonServerWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/EffectWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ElectionWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/FireSaleWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/SkillsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/Components.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/ProgressComponent.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, reviews needed

#963 Smooth AOTE
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/CameraMixin.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/PingMeasurerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/SmoothAOTE.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#1145 Fix dungeon score not working when fancy tab hud is disabled
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/PlayerListManager.java
Labels: bug, merge me please

#1056 add enchantment abbreviations as slot text
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EnchantmentLevelAdder.java
  src/test/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EnchantmentLevelAdderTest.java
Labels: new feature, merge me please

#1106 Add client game test
  .github/workflows/beta.yml
  build.gradle
  gradle.properties
  src/main/java/de/hysky/skyblocker/SkyblockerGameTest.java
  src/main/java/de/hysky/skyblocker/debug/Debug.java
  src/main/java/de/hysky/skyblocker/debug/SnapshotDebug.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/BarPositioner.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBarType.java
  src/main/resources/fabric.mod.json
  src/main/resources/templates/skyblocker_render.png
Labels: reviews needed, merge me please

#1115 Add Teleport Maze Solver + small things
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonClass.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/TeleportMaze.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretsTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonPlayerWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/PlayerComponent.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, new feature, reviews needed, merge me please

#1137 Fix JGit using insteadOfs (how?)
  src/main/java/de/hysky/skyblocker/mixins/jgit/UrlConfigMixin.java
  src/main/resources/skyblocker.mixins.json
Labels: bug, reviews needed, merge me please

#1144 Remove unused setting
  src/main/java/de/hysky/skyblocker/config/categories/ChatCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/ChatConfig.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/it_it.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: bug, merge me please

#1146 Fix forge HUD tooltips about locked slots 5,6,7
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ForgeWidget.java
Labels: bug, merge me please
