Repository SkyblockerMod/Skyblocker, pull requests merged in 2025-08, with the labels that each got.

#1551 fix tooltip adders not working on firmament's REI
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
Labels: bug, compatibility, merge me please

#1561 Disable Chat Rule if Regex Pattern is invalid
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRule.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#1439 Backup Configs
  src/main/java/de/hysky/skyblocker/SkyblockerMod.java
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/java/de/hysky/skyblocker/config/backup/ConfigBackupManager.java
  src/main/java/de/hysky/skyblocker/config/backup/ConfigBackupScreen.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/AvgBinTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/info/DataTooltipInfo.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/info/SimpleTooltipInfo.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1560 Allow moving Powder Mining Tracker Widget
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/PowderMiningTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/PowderMiningWidget.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1170 Museum HUD
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREIClientPlugin.java
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/item/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/CraftPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/MuseumTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeResults.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/Donation.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/DonationButton.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/ItemFilter.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/ItemSorter.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/MuseumManager.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/MuseumUtils.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/PriceData.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1556 draggable visitor helper
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
Labels: new feature, merge me please

#1554 caxton compat for outlined text
  src/main/java/de/hysky/skyblocker/compatibility/CaxtonCompatibility.java
  src/main/java/de/hysky/skyblocker/utils/render/HudHelper.java
Labels: bug, compatibility, merge me please

#1569 fixes skyblocker settings button tooltip
  src/main/java/de/hysky/skyblocker/config/SkyblockerConfigManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#1533 Better Party Finder Settings Page Bug Fixes
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/FinderSettingsContainer.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/OptionDropdownWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/PartyFinderScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/RangedValueWidget.java
Labels: bug, merge me please

#1549 fix AttributeLevelHelper not showing in config and make CommissionLabels work when CommsWidget is disabled
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/CommissionLabels.java
  src/main/java/de/hysky/skyblocker/skyblock/hunting/AttributeLevelHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/CommsWidget.java
Labels: bug, merge me please

#1577 Update Enchantment Abbreviations for SB 0.23.3
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EnchantmentLevelAdder.java
Labels: bug, merge me please

#1574 Fix Attribute Shards
  src/main/java/de/hysky/skyblocker/skyblock/hunting/Attributes.java
Labels: bug, merge me please

#1571 Museum overlay changes
  src/main/java/de/hysky/skyblocker/skyblock/item/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/DonationButton.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/MuseumUtils.java
Labels: bug, merge me please

#1580 Optimize ice fill solver from around 270 ms to around 90 ms
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFill.java
  src/test/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/IceFillTest.java
Labels: merge me please

#1441 Hide item slots in solvers
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/ColorTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/StartsWithTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/ExperimentSolver.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolver.java
  src/main/java/de/hysky/skyblocker/utils/container/StackDisplayModifier.java
Labels: new feature, merge me please

#1435 Improvements to Teleport overlay and smooth AOTE
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/SmoothAOTE.java
  src/main/java/de/hysky/skyblocker/skyblock/TeleportOverlay.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1485 Use Line Feed
  .gitattributes
  build.gradle
  gradlew.bat
Labels: bug, merge me please

#1579 Add Sellable Dungeon Items Highlighter
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/SalvageHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/SellableItemsHighlighter.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1589 Fix REI Skyblock Info Display Changing Recipe Quantities
  src/main/java/de/hysky/skyblocker/compatibility/rei/info/SkyblockInfoDisplayGenerator.java
Labels: bug, merge me please

#1588 Fix Sellable Items Highlighter Slots
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/SellableItemsHighlighter.java
Labels: bug, merge me please

#1585 Fix Enchanted Books in REI Item List
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockItemComparator.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREICommonPlugin.java
  src/main/resources/fabric.mod.json
Labels: bug, merge me please

#1592 Rename Enchanted Book Collapsible Categories to the Enchantment Name
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREIClientPlugin.java
Labels: merge me please

#1591 Reload Recipes After the Item Repository Has Finished Loading
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
Labels: bug, merge me please

#1545 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/ar_aa.json
  src/main/resources/assets/skyblocker/lang/da_dk.json
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/hu_hu.json
  src/main/resources/assets/skyblocker/lang/id_id.json
  src/main/resources/assets/skyblocker/lang/it_it.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/ko_kr.json
  src/main/resources/assets/skyblocker/lang/pl_pl.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/tr_tr.json
  src/main/resources/assets/skyblocker/lang/uk_ua.json
  src/main/resources/assets/skyblocker/lang/vi_vn.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#1584 Update spotless and clean up en_us.json
  .editorconfig
  build.gradle
  src/main/java/de/hysky/skyblocker/config/backup/ConfigBackupScreen.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/hu_hu.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/uk_ua.json
  src/main/resources/assets/skyblocker/lang/vi_vn.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: bug, reviews needed

#1601 Support Basic and Advanced Gardening Hoes for Mouse Lock
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
Labels: new feature, merge me please

#1603 Fix: Change `/skyblocker protectItem` to always send output without respecting the config option
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemProtection.java
Labels: bug, merge me please

#1606 Improve searchability of Tuner Solver
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/assets/skyblocker/lang/hu_hu.json
Labels: merge me please

#1604 Keybind Shortcuts
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/mixins/KeyBindingMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesHandler.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/AccessoriesHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/MuseumItemCache.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutKeyBinding.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/Shortcuts.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/speedpreset/SpeedPresets.java
  src/main/java/de/hysky/skyblocker/utils/CodecUtils.java
  src/main/java/de/hysky/skyblocker/utils/data/JsonData.java
  src/main/java/de/hysky/skyblocker/utils/data/ProfiledData.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
  src/test/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsTest.java
Labels: new feature, merge me please

#1607 [Alpha] Add Dungeonbreaker Simple Chat Filter
  src/main/java/de/hysky/skyblocker/config/categories/ChatCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/ChatConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/filters/DungeonBreakerFilter.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatMessageListener.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/chat/filters/DungeonBreakerFilterTest.java
Labels: new feature, merge me please, alpha-net

#1610 Remove background blur on Fancy Party Finder Screen
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/partyfinder/PartyFinderScreen.java
Labels: merge me please

#1617 Fix Update Notification Channel Names Not Showing Correctly
  src/main/java/de/hysky/skyblocker/UpdateNotifications.java
Labels: bug, merge me please

#1621 5.7.0
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
Labels: merge me please

#1614 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/es_es.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/hu_hu.json
  src/main/resources/assets/skyblocker/lang/it_it.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/vi_vn.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please
