Repository SkyblockerMod/Skyblocker, pull requests merged in 2025-09, with the labels that each got.

#1624 Update item secrets detection
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretWaypoint.java
Labels: bug, merge me please

#1637 Use disable slot texture
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/CompactorPreviewTooltipComponent.java
Labels: merge me please

#1628 Change halfBarColor to FFFF00
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
Labels: bug, merge me please

#1625 Add Call Trevor Prompt
  src/main/java/de/hysky/skyblocker/config/categories/OtherLocationsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/OtherLocationsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/barn/CallTrevor.java
  src/main/java/de/hysky/skyblocker/utils/chat/ChatMessageListener.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please, alpha-net

#1633 Shortcut keybind combos
  src/main/java/de/hysky/skyblocker/mixins/KeyBindingMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/KeybindWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutKeyBinding.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/Shortcuts.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigListWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsConfigScreen.java
  src/test/java/de/hysky/skyblocker/skyblock/shortcut/ShortcutsTest.java
Labels: new feature, merge me please

#1642 Fix Bestiary Regex
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/BestiaryLevelAdder.java
Labels: merge me please

#1559 [Feat] Wiki Lookup refactor
  src/main/java/de/hysky/skyblocker/compatibility/rei/info/SkyblockInfoCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixins/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/PetCache.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorWikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/PetInfo.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockInventoryScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/item/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/wikilookup/EnchantmentBookItemLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/wikilookup/EventCalendarLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/wikilookup/PetItemLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/wikilookup/RegularItemLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/wikilookup/VisitorLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/wikilookup/WikiLookup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/wikilookup/WikiLookupManager.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeResults.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/DonationButton.java
  src/main/java/de/hysky/skyblocker/skyblock/museum/MuseumManager.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: merge me please

#1568 quick nav item selector
  src/main/java/de/hysky/skyblocker/config/categories/QuickNavigationCategory.java
  src/main/java/de/hysky/skyblocker/config/screens/quicknav/ItemSelectionScreen.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/SearchableGridWidget.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1572 hunting added coralot & shellwise highlight
  src/main/java/de/hysky/skyblocker/config/categories/HuntingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HuntingConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/glow/adder/GalateaGlowAdder.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1613 Add chat rules insert regex capture group support
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRule.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesHandler.java
  src/test/java/de/hysky/skyblocker/skyblock/chat/ChatRuleTest.java
Labels: new feature, merge me please

#1635 Item bg rarity color improvement and preventing some loading exceptions
  src/main/java/de/hysky/skyblocker/injected/SkyblockerStack.java
  src/main/java/de/hysky/skyblocker/mixins/ItemStackMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/PetCache.java
  src/main/java/de/hysky/skyblocker/skyblock/auction/widgets/RarityWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockInventoryScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockItemRarity.java
  src/main/java/de/hysky/skyblocker/skyblock/item/background/adders/ItemRarityBackground.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/Waypoints.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: bug, merge me please

#1641 Add back name sorting options
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/PlayerListManager.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/PlayerListWidget.java
  src/main/java/de/hysky/skyblocker/utils/Constants.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1651 Improve toughness calculation
  src/main/java/de/hysky/skyblocker/skyblock/foraging/SweepOverlay.java
Labels: merge me please

#1658 Disable REI Integration when out of SkyBlock
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREIClientPlugin.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREICommonPlugin.java
Labels: merge me please

#1676 Remove Daedalus Axe from Farming Tools
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
Labels: merge me please, small change

#1678 Update Spider's Den Relic Position
  src/main/resources/assets/skyblocker/spidersden/relics.json
Labels: reviews needed, small change

#1664 lasso hud
  src/main/java/de/hysky/skyblocker/config/categories/HuntingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HuntingConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/hunting/LassoHud.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1677 Fix Cactus Knife Blocks per Second in Farming Hud
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
Labels: merge me please

#1692 fix rendering order of status bars
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBar.java
Labels: bug, merge me please

#1671 Calculator improvements
  src/main/java/de/hysky/skyblocker/skyblock/calculators/CalculatorCommand.java
  src/main/java/de/hysky/skyblocker/skyblock/calculators/SignCalculator.java
  src/main/java/de/hysky/skyblocker/utils/Calculator.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/utils/CalculatorTest.java
Labels: merge me please

#1685 add waypoint type config to ender node helper
  src/main/java/de/hysky/skyblocker/config/categories/OtherLocationsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/OtherLocationsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EnderNodes.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1693 getrdhytfyifuyufuk
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBar.java
Labels: bug, merge me please

#1696 Fix location check for Lasso Hud
  src/main/java/de/hysky/skyblocker/skyblock/hunting/LassoHud.java
Labels: bug, merge me please, small change

#1691 add iris shader support to renderpipelines
  src/main/java/de/hysky/skyblocker/compatibility/IrisCompatibility.java
  src/main/java/de/hysky/skyblocker/utils/render/SkyblockerRenderPipelines.java
  src/main/resources/fabric.mod.json
Labels: bug, compatibility, merge me please

#1649 Make various icons on tablist widgets work with custom resource packs
  src/main/java/de/hysky/skyblocker/skyblock/galatea/SweepDetailsHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/item/HeadTextures.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Ico.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/EffectWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/PowderWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ServerWidget.java
Labels: new feature, merge me please

#1694 Dungeon Chest Profit Changes
  src/main/java/de/hysky/skyblocker/skyblock/ChestValue.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/CroesusProfit.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#1700 Add support for NPC Shop Recipes in REI
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREIClientPlugin.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeResults.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipes/SkyblockNpcShopRecipe.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipes/SkyblockRecipe.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1705 Fix item count in the Gemstones Sack
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: merge me please

#1709 Fix Compact Damage for Tarantula Armor Ability
  src/main/java/de/hysky/skyblocker/skyblock/CompactDamage.java
Labels: bug, merge me please, small change
