Repository SkyblockerMod/Skyblocker, pull requests merged in 2025-03, with the labels that each got.

#1028 Health bars
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/HealthBars.java
  src/main/java/de/hysky/skyblocker/utils/ColorUtils.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/utils/ColorUtilsTest.java
Labels: new feature, merge me please

#1118 Garden Tweaks & Features
  src/main/java/de/hysky/skyblocker/config/categories/CrimsonIsleCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/FarmingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/FarmingConfig.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobBoundingBoxes.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/Visitor.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
  src/main/java/de/hysky/skyblocker/utils/Formatters.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
  src/main/java/de/hysky/skyblocker/utils/Utils.java
  src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/utils/FormattersTest.java
Labels: new feature, merge me please

#1147 Event Start Time in Calendar menu
  src/main/java/de/hysky/skyblocker/config/categories/GeneralCategory.java
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/CalendarStartTimeTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/UpcomingEventsTab.java
  src/main/java/de/hysky/skyblocker/utils/RegexUtils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1156 Fossil Solver
  src/main/java/de/hysky/skyblocker/config/categories/MiningCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/MiningConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/fossil/FossilCalculations.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/fossil/FossilSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/fossil/FossilTypes.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/fossil/Structures.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/TooltipManager.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/test/java/de/hysky/skyblocker/skyblock/dwarven/fossil/FossilSolverTest.java
Labels: new feature, merge me please

#1172 Fabric updates
  .github/workflows/beta.yml
  build.gradle
  buildSrc/src/main/java/de/hysky/skyblocker/hud/HudInjectClassVisitor.java
  buildSrc/src/main/java/de/hysky/skyblocker/hud/HudProcessor.java
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/gametest/java/de/hysky/skyblocker/SkyblockerGameTest.java
  src/gametest/resources/fabric.mod.json
  src/gametest/resources/templates/skyblocker_render.png
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/events/HudRenderEvents.java
  src/main/java/de/hysky/skyblocker/mixins/InGameHudMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonMap.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScoreHUD.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/FireFreezeStaffTimer.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/GlaciteColdOverlay.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/PowderMiningTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/config/WidgetsConfigurationScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/config/preview/PreviewTab.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/config/preview/PreviewWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/ScreenBuilder.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/WidgetManager.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/pipeline/PositionRule.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/pipeline/WidgetPositioner.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/PlayerListManager.java
  src/main/java/de/hysky/skyblocker/utils/render/title/TitleContainer.java
  src/main/resources/fabric.mod.json
Labels: reviews needed

#1175 Add teleport overlay color config
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/TeleportOverlay.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please, small change

#1185 Migrate to formatters
  src/main/java/de/hysky/skyblocker/skyblock/accessories/newyearcakes/NewYearCakesHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/calculators/CalculatorCommand.java
  src/main/java/de/hysky/skyblocker/skyblock/calculators/SignCalculator.java
  src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/ChocolateFactorySolver.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/profittrackers/PowderMiningTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/end/EndHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EssenceShopAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EvolvingItemAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/YourEssenceAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/BitsHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/EssenceShopPrice.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/StackingEnchantProgressTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/collections/GenericCategory.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/dungeons/DungeonClassWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/Pet.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/skills/SkillWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/slayers/SlayerWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/utils/ProfileViewerUtils.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/hud/SlayerHudWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/PowderWidget.java
  src/main/java/de/hysky/skyblocker/utils/Formatters.java
  src/test/java/de/hysky/skyblocker/utils/FormattersTest.java
Labels: reviews needed

#1197 Fix empty validLocations set failing to be decoded
  src/main/java/de/hysky/skyblocker/skyblock/chat/ChatRulesConfigScreen.java
  src/main/java/de/hysky/skyblocker/utils/CodecUtils.java
  src/main/java/de/hysky/skyblocker/utils/Location.java
  src/test/java/de/hysky/skyblocker/skyblock/chat/ChatRuleTest.java
Labels: bug, merge me please, small change

#1200 Fix dungeon entrance room physical pos being detected incorrectly
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
Labels: merge me please, high priority

#1163 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/da_dk.json
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/id_id.json
  src/main/resources/assets/skyblocker/lang/it_it.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/lol_us.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/vi_vn.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#1203 Update Ice Fill Room
  src/main/resources/assets/skyblocker/dungeons/catacombs/puzzle/ice-path.skeleton
  src/test/resources/assets/skyblocker/dungeons/dungeonrooms/catacombs/Puzzle/Ice-Path.skeleton
Labels: bug, reviews needed

#1205 Render Layer Migration
  src/main/java/de/hysky/skyblocker/skyblock/HealthBars.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/SkyblockerRenderLayers.java
Labels: bug, reviews needed, compatibility

#1206 Remove Skyblock Time Logging
  src/main/java/de/hysky/skyblocker/utils/SkyblockTime.java
Labels: bug, reviews needed, small change

#1207 Auto Pet support for the Pet Cache
  src/main/java/de/hysky/skyblocker/skyblock/PetCache.java
  src/main/java/de/hysky/skyblocker/skyblock/item/SkyblockItemRarity.java
Labels: bug, reviews needed

#1208 Update Ordered Waypoints Tooltip
  src/main/java/de/hysky/skyblocker/skyblock/Tips.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, reviews needed, small change

#1210 Fix dungeon floor ordering in pv
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/dungeons/DungeonFloorRunsWidget.java
Labels: bug, reviews needed, small change

#1209 Simplify hiding world loading screens
  src/main/java/de/hysky/skyblocker/mixins/DownloadingTerrainScreenMixin.java
  src/main/java/de/hysky/skyblocker/mixins/MinecraftClientMixin.java
  src/main/java/de/hysky/skyblocker/mixins/ScreenMixin.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/BasePlaceholderScreen.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/JoinWorldPlaceholderScreen.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ReconfiguringPlaceholderScreen.java
  src/main/resources/skyblocker.mixins.json
Labels: bug, reviews needed, small change

#1212 Add Moby-Duck as an evolving item
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EvolvingItemAdder.java
Labels: merge me please, alpha-net

#1213 Fix catacombs level adder showing incorrect levels
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CatacombsLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/PotionLevelAdder.java
Labels: bug, merge me please, small change

#1214 Update mod to 5.1.0
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
Labels: merge me please

#1211 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: reviews needed

#1217 Fix swing animation causing right clicks to also send left clicks
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayerInteractionManagerMixin.java
Labels: bug, merge me please, high priority

#1218 fix leap overlay opening outside of dungeons
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenProviderMixin.java
Labels: merge me please

#1216 fix fossil solver bugs
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/fossil/FossilCalculations.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/fossil/FossilTypes.java
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/fossil/Structures.java
  src/test/java/de/hysky/skyblocker/skyblock/dwarven/fossil/FossilSolverTest.java
Labels: bug, merge me please

#1219 Visitor Helper fixes
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
Labels: merge me please

#1221 5.1.1
  CHANGELOG.md
  gradle.properties
Labels: merge me please

#1224 Fix fossil solver again
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/fossil/FossilSolver.java
Labels: merge me please

#1225 the final visitor fix hopefully
  src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
Labels: merge me please

#1226 5.1.2
  CHANGELOG.md
  README.md
  gradle.properties
Labels: reviews needed
