Repository SkyblockerMod/Skyblocker, pull requests merged in 2025-07, with the labels that each got.

#1449 Fix Farming Hud Skill EXP not working when Fancy Status bars are disabled
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
Labels: bug, merge me please

#1457 Show Input Calculator on Bazaar flip input sign
  src/main/java/de/hysky/skyblocker/mixins/SignEditScreenMixin.java
Labels: merge me please

#1444 Translations update from hysky translate
  src/main/resources/assets/skyblocker/lang/de_de.json
  src/main/resources/assets/skyblocker/lang/en_ca.json
  src/main/resources/assets/skyblocker/lang/fr_fr.json
  src/main/resources/assets/skyblocker/lang/hu_hu.json
  src/main/resources/assets/skyblocker/lang/ja_jp.json
  src/main/resources/assets/skyblocker/lang/pt_br.json
  src/main/resources/assets/skyblocker/lang/ru_ru.json
  src/main/resources/assets/skyblocker/lang/vi_vn.json
  src/main/resources/assets/skyblocker/lang/zh_cn.json
  src/main/resources/assets/skyblocker/lang/zh_tw.json
Labels: merge me please

#1460 Fix Guardian Health Text Crash
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/GuardianHealth.java
Labels: merge me please

#1450 Add other wooden doors to fetchur
  src/main/java/de/hysky/skyblocker/skyblock/dwarven/Fetchur.java
Labels: merge me please

#1474 Fix skyblocker's REI compat taking priority over Firmament's
  gradle.properties
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREIClientPlugin.java
Labels: merge me please

#1452 Bestiary Level Slot Text & Slot Text Fixes
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/BestiaryLevelAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/CollectionAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EssenceShopAdder.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1477 Fix Smooth AOTE working in Dojo
  src/main/java/de/hysky/skyblocker/skyblock/SmoothAOTE.java
Labels: bug, merge me please

#1476 Support Item Price Lookup for Items in the Recipe Book
  src/main/java/de/hysky/skyblocker/skyblock/item/ItemPrice.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/recipebook/SkyblockRecipeResults.java
Labels: merge me please

#1427 Add support for new shards in Search Overlay
  gradle.properties
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
  src/main/java/de/hysky/skyblocker/utils/ItemUtils.java
Labels: merge me please

#1454 Disable All Command
  src/main/java/de/hysky/skyblocker/DisableAll.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1464 Dungeon splits
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/events/DungeonEvents.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonSplitsWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/screenbuilder/WidgetManager.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/TableWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/TableComponent.java
  src/main/java/de/hysky/skyblocker/utils/CodecUtils.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1480 Refactor NEURepoManager
  src/main/java/de/hysky/skyblocker/skyblock/ItemPickupWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/SackItemAutocomplete.java
  src/main/java/de/hysky/skyblocker/skyblock/chat/SackMessagePrice.java
  src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/adders/CraftPriceTooltip.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemStackBuilder.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/StackOverlays.java
  src/main/java/de/hysky/skyblocker/skyblock/profileviewer/inventory/Pet.java
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/FairySouls.java
  src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java
Labels: merge me please

#1487 fix quick nav offset
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
Labels: merge me please

#1486 Livid Highlighter Localization Cleanup + Custom Color Option
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1430 Tuner solver
  src/main/java/de/hysky/skyblocker/config/categories/ForagingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/ForagingConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/bazaar/ReorderHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/ColorTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/LightsOnTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/OrderTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/SameColorTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/terminal/StartsWithTerminal.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/ChronomatronSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/SuperpairsSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/experiment/UltrasequencerSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/galatea/TunerSolver.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/SlotTextManager.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolver.java
  src/main/java/de/hysky/skyblocker/utils/container/ContainerSolverManager.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1507 Remove [SKYBLOCKER] Prefix from Livid Color Title
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java
Labels: bug, merge me please

#1515 Add a description to quick navigation toggle
  src/main/java/de/hysky/skyblocker/config/categories/QuickNavigationCategory.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: documentation, merge me please

#1508 Add a Config Option to Disable Bazaar Reorder Helper
  src/main/java/de/hysky/skyblocker/config/categories/HelperCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/HelperConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/bazaar/ReorderHelper.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, question, merge me please

#1509 Fix Max Pet Level for Jade Dragon and Searching for Null Ovoids in Search Overlay
  src/main/java/de/hysky/skyblocker/skyblock/searchoverlay/SearchOverManager.java
Labels: bug, merge me please

#1488 Make quicknav grab backgroundScreen
  src/main/java/de/hysky/skyblocker/mixins/accessors/PopupBackgroundAccessor.java
  src/main/java/de/hysky/skyblocker/skyblock/quicknav/QuickNavButton.java
  src/main/resources/skyblocker.mixins.json
Labels: bug, merge me please

#1434 waypoint import options + fixes
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/Waypoints.java
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/WaypointsShareScreen.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/NamedWaypoint.java
  src/main/java/de/hysky/skyblocker/utils/waypoint/WaypointGroup.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#1432 Strong and independent bars
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/EditBarWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/FancyStatusBars.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBar.java
  src/main/java/de/hysky/skyblocker/skyblock/fancybars/StatusBarsConfigScreen.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1380 [WIP] Standardized text style
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: merge me please

#1527 use longs to prevent overflow in FarmingHud
  src/main/java/de/hysky/skyblocker/skyblock/garden/FarmingHud.java
Labels: merge me please

#1523 Only Send "Mimic Dead" Message to Party Chat
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonScore.java
Labels: merge me please

#1520 smooth aote fix
  src/main/java/de/hysky/skyblocker/skyblock/StatusBarTracker.java
Labels: merge me please

#1423 Customize player heads
  src/main/java/de/hysky/skyblocker/config/configs/GeneralConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ComponentHolderMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/CustomHelmetTextures.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/CustomizeArmorScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/HeadSelectionWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java
Labels: new feature, merge me please

#1496 REI /viewrecipe Crafting, Skyblock Info Display
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockTransferHandler.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/SkyblockerREIClientPlugin.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/info/SkyblockInfoCategory.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/info/SkyblockInfoDisplay.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/info/SkyblockInfoDisplayGenerator.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/recipe/SkyblockRecipeCategory.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/recipe/SkyblockRecipeDisplay.java
  src/main/java/de/hysky/skyblocker/compatibility/rei/recipe/SkyblockRecipeDisplayGenerator.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1493 Fix Sea Lumies being highlighted when highlighter is disabled
  src/main/java/de/hysky/skyblocker/skyblock/galatea/SeaLumiesHighlighter.java
Labels: bug, merge me please

#1239 Fancy Dungeon Map
  src/main/java/de/hysky/skyblocker/config/categories/DungeonsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/DungeonsConfig.java
  src/main/java/de/hysky/skyblocker/events/DungeonEvents.java
  src/main/java/de/hysky/skyblocker/mixins/HandledScreenProviderMixin.java
  src/main/java/de/hysky/skyblocker/mixins/MapRendererMixin.java
  src/main/java/de/hysky/skyblocker/mixins/accessors/MapStateAccessor.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/ArrowPoisonWarning.java
  src/main/java/de/hysky/skyblocker/skyblock/crimson/kuudra/DangerWarning.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonClass.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonMap.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/LeapOverlay.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/puzzle/boulder/Boulder.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonMapUtils.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/DungeonPlayerManager.java
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/secrets/SecretsTracker.java
  src/main/java/de/hysky/skyblocker/skyblock/fishing/FishingHelper.java
  src/main/java/de/hysky/skyblocker/skyblock/rift/HealingMelonIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/demonlord/FirePillarAnnouncer.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/vampire/ManiaIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/vampire/StakeIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/slayers/boss/vampire/TwinClawsIndicator.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/DungeonPlayerWidget.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/title/TitleContainer.java
  src/main/resources/assets/skyblocker/lang/en_us.json
  src/main/resources/skyblocker.mixins.json
Labels: new feature, merge me please

#1484 Waypoints import fix
  src/main/java/de/hysky/skyblocker/skyblock/waypoint/Waypoints.java
Labels: bug, merge me please

#1387 add option to split sack and inventory notifications of pickup widget
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/ItemPickupWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/ComponentBasedWidget.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/Component.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/widget/component/SeparatorComponent.java
Labels: new feature, merge me please

#1540 Fix black glow on dungeon mobs when Class-Based Player Glow is enabled
  src/main/java/de/hysky/skyblocker/skyblock/dungeon/DungeonClass.java
  src/main/java/de/hysky/skyblocker/skyblock/entity/glow/adder/DungeonGlowAdder.java
Labels: bug, merge me please

#1490 Rename item GUI
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/CustomItemNames.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/ColorPopup.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/CustomizeNameScreen.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/visitor/BaseVisitor.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/visitor/GetClickedPositionVisitor.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/visitor/GetRenderWidthVisitor.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/visitor/GetStyleVisitor.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/visitor/InsertTextVisitor.java
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/visitor/SetStyleVisitor.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ARGBTextInput.java
  src/main/java/de/hysky/skyblocker/utils/render/gui/ColorPickerWidget.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1542 fix bug and set text field focused by default
  src/main/java/de/hysky/skyblocker/skyblock/item/custom/screen/name/CustomizeNameScreen.java
Labels: merge me please

#1544 5.6.0
  CHANGELOG.md
  FEATURES.md
  README.md
  gradle.properties
Labels: merge me please

#1546 feat: Option for Evolving Items and New Year Cake Slot Text
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/EvolvingItemAdder.java
  src/main/java/de/hysky/skyblocker/skyblock/item/slottext/adders/NewYearCakeAdder.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: bug, merge me please

#1317 Gyro wand radius overlay
  src/main/java/de/hysky/skyblocker/config/categories/UIAndVisualsCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/UIAndVisualsConfig.java
  src/main/java/de/hysky/skyblocker/skyblock/GyroOverlay.java
  src/main/java/de/hysky/skyblocker/utils/render/RenderHelper.java
  src/main/java/de/hysky/skyblocker/utils/render/SkyblockerRenderLayers.java
  src/main/java/de/hysky/skyblocker/utils/render/SkyblockerRenderPipelines.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1403 Add Tree Break Progress HUD
  src/main/java/de/hysky/skyblocker/config/categories/ForagingCategory.java
  src/main/java/de/hysky/skyblocker/config/configs/ForagingConfig.java
  src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/de/hysky/skyblocker/skyblock/galatea/TreeBreakProgressHud.java
  src/main/java/de/hysky/skyblocker/skyblock/tabhud/util/Ico.java
  src/main/resources/assets/skyblocker/lang/en_us.json
Labels: new feature, merge me please

#1557 Fix Garden Plots Widget tooltips being offset (on 1.21.6+)
  src/main/java/de/hysky/skyblocker/skyblock/garden/GardenPlotsWidget.java
Labels: merge me please
